#include"data.h"
#include"command_event.h"
#include"hci.h"
/********************************hci event define*****************************/
static _u8  hci_event_buffer[256];
static _u16 hciCommandOpcode; 
#define HCI_NUMBER_OF_COMMAND_PACKETS               1


static void* hci_event(_s32 eventCode,_u8 len,bt_hci_event_t** event)
{
    *event = (bt_hci_event_t*)hci_event_buffer;
    (*event)->eventCode = eventCode;
    (*event)->length    = len;
    return (*event)->parameter;
}


typedef struct _PACKED
{
    _u8  status;
    _u8  numOfCmd;
    _u16 opcode;
}hci_event_command_status_t;
static bt_hci_event_t* hci_command_status_event(_u16 opcode,controller_error_code_e status)
{
    bt_hci_event_t* event = (bt_hci_event_t*)hci_event_buffer;
    hci_event_command_status_t *param = (hci_event_command_status_t*)event->parameter;
    event->eventCode = HCI_COMMAND_STATUS_EVENT;
    event->length = sizeof(hci_event_command_status_t);
    param->numOfCmd = HCI_NUMBER_OF_COMMAND_PACKETS;
    param->opcode = opcode;
    param->status = status;
    return event;
}

typedef struct _PACKED
{
    _u8  numOfCmd;
    _u16 opcode;
    _u8  data[0];
}hci_event_command_complete_t;

static void* hci_command_complete_event(_u16 opcode,_u8 len,bt_hci_event_t **event)
{
    hci_event_command_complete_t * command =  (hci_event_command_complete_t*)hci_event((_s32)HCI_COMMAND_COMPLETE_EVENT,len+3,event);
    command->numOfCmd = HCI_NUMBER_OF_COMMAND_PACKETS;
    command->opcode   = opcode;
    return command->data;
}

/********************************hci command define*****************************/
typedef controller_error_code_e(*hci_command_f)(_u8* data,_u8 length,bt_hci_event_t** event);

typedef struct 
{
	_u32                       ocf;
	hci_command_f              process;
}hci_command_t;

#define HCI_COMMAND_LIST_LENGTH(hci_command_list)      (sizeof(hci_command_list)/sizeof(hci_command_list[0]))
#define HCI_COMMAND_LENGTH(hci_command_array)          (sizeof(hci_command_array)/sizeof(hci_command_array[0]))

static const hci_command_t hci_command_link_control_list[] =
{
    {HCI_INQUIRY_COMMAND, NULL},
    {HCI_INQUIRY_CANCEL_COMMAND, NULL},
    {HCI_PERIODIC_INQUIRY_MODE_COMMAND, NULL},
    {HCI_EXIT_PERIODIC_INQUIRY_MODE_COMMAND, NULL},
    {HCI_CREATE_CONNECTION_COMMAND, NULL},
    {HCI_DISCONNECT_COMMAND, NULL},
    {HCI_CREATE_CONNECTION_CANCEL_COMMAND, NULL},
    {HCI_ACCEPT_CONNECTION_REQUEST_COMMAND, NULL},
    {HCI_REJECT_CONNECTION_REQUEST_COMMAND, NULL},
    {HCI_LINK_KEY_REQUEST_REPLY_COMMAND, NULL},
    {HCI_LINK_KEY_REQUEST_NEGATIVE_REPLY_COMMAND, NULL},
    {HCI_PIN_CODE_REQUEST_REPLY_COMMAND, NULL},
    {HCI_PIN_CODE_REQUEST_NEGATIVE_REPLY_COMMAND, NULL},
    {HCI_CHANGE_CONNECTION_PACKET_TYPE_COMMAND, NULL},
    {HCI_AUTHENTICATION_REQUESTED_COMMAND, NULL},
    {HCI_SET_CONNECTION_ENCRYPTION_COMMAND, NULL},
    {HCI_CHANGE_CONNECTION_LINK_KEY_COMMAND, NULL},
    {HCI_LINK_KEY_SELECTION_COMMAND, NULL},
    {HCI_REMOTE_NAME_REQUEST_COMMAND, NULL},
    {HCI_READ_REMOTE_SUPPORTED_FEATURES_COMMAND, NULL},
    {HCI_READ_REMOTE_EXTENDED_FEATURES_COMMAND, NULL},
    {HCI_READ_REMOTE_VERSION_INFORMATION_COMMAND, NULL},
    {HCI_READ_CLOCK_OFFSET_COMMAND, NULL},
    {HCI_READ_LMP_HANDLE_COMMAND, NULL},
    {HCI_SETUP_SYNCHRONOUS_CONNECTION_COMMAND, NULL},
    {HCI_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND, NULL},
    {HCI_REJECT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND, NULL},
    {HCI_IO_CAPABILITY_REQUEST_REPLY_COMMAND, NULL},
    {HCI_USER_CONFIRMATION_REQUEST_REPLY_COMMAND, NULL},
    {HCI_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_COMMAND, NULL},
    {HCI_USER_PASSKEY_REQUEST_REPLY_COMMAND, NULL},
    {HCI_USER_PASSKEY_REQUEST_NEGATIVE_REPLY_COMMAND, NULL},
    {HCI_REMOTE_OOB_DATA_REQUEST_REPLY_COMMAND, NULL},
    {HCI_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_COMMAND, NULL},
    {HCI_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_COMMAND, NULL},
    {HCI_ENHANCED_SETUP_SYNCHRONOUS_CONNECTION_COMMAND, NULL},
    {HCI_ENHANCED_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND, NULL},
    {HCI_TRUNCATED_PAGE_COMMAND, NULL},
    {HCI_TRUNCATED_PAGE_CANCEL_COMMAND, NULL},
    {HCI_SET_CONNECTIONLESS_PERIPHERAL_BROADCAST_COMMAND, NULL},
    {HCI_SET_CONNECTIONLESS_PERIPHERAL_BROADCAST_RECEIVE_COMMAND, NULL},
    {HCI_START_SYNCHRONIZATION_TRAIN_COMMAND, NULL},
    {HCI_RECEIVE_SYNCHRONIZATION_TRAIN_COMMAND, NULL},
    {HCI_REMOTE_OOB_EXTENSION_DATA_REQUEST_REPLY_COMMAND, NULL}
};

static const hci_command_t hci_command_link_policy_list[] =
{
    {HCI_HOLD_MODE_COMMAND, NULL},
    {HCI_SNIFF_MODE_COMMAND, NULL},
    {HCI_EXIT_SNIFF_MODE_COMMAND, NULL},
    {HCI_QOS_SETUP_COMMAND, NULL},
    {HCI_ROLE_DISCOVERY_COMMAND, NULL},
    {HCI_SWITCH_ROLE_COMMAND, NULL},
    {HCI_READ_LINK_POLICY_SETTINGS_COMMAND, NULL},
    {HCI_WRITE_LINK_POLICY_SETTINGS_COMMAND, NULL},
    {HCI_READ_DEFAULT_LINK_POLICY_SETTINGS_COMMAND, NULL},
    {HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS_COMMAND, NULL},
    {HCI_FLOW_SPECIFICATION_COMMAND, NULL},
    {HCI_SNIFF_SUBRATING_COMMAND, NULL}
};

struct hci_command_reset_retParam_t
{
    _u8 status;
};
controller_error_code_e hci_reset_command(_u8* data,_u8 length,bt_hci_event_t** event)
{
    struct hci_command_reset_retParam_t* param;
    controller_error_code_e status = ll_reset();
    if(status == SUCCESS)
    {
        param = hci_command_complete_event(hciCommandOpcode,sizeof(struct hci_command_reset_retParam_t),event);
        param->status = (_u8)SUCCESS;

    }
    return SUCCESS;
}

static const hci_command_t hci_command_controller_baseband_list[] =
{
    {HCI_SET_EVENT_MASK_COMMAND, NULL},
    {HCI_RESET_COMMAND, hci_reset_command},
    {HCI_SET_EVENT_FILTER_COMMAND, NULL},
    {HCI_FLUSH_COMMAND, NULL},
    {HCI_READ_PIN_TYPE_COMMAND, NULL},
    {HCI_WRITE_PIN_TYPE_COMMAND, NULL},
    {HCI_READ_STORED_LINK_KEY_COMMAND, NULL},
    {HCI_WRITE_STORED_LINK_KEY_COMMAND, NULL},
    {HCI_DELETE_STORED_LINK_KEY_COMMAND, NULL},
    {HCI_WRITE_LOCAL_NAME_COMMAND, NULL},
    {HCI_READ_LOCAL_NAME_COMMAND, NULL},
    {HCI_READ_CONNECTION_ACCEPT_TIMEOUT_COMMAND, NULL},
    {HCI_WRITE_CONNECTION_ACCEPT_TIMEOUT_COMMAND, NULL},
    {HCI_READ_PAGE_TIMEOUT_COMMAND, NULL},
    {HCI_WRITE_PAGE_TIMEOUT_COMMAND, NULL},
    {HCI_READ_SCAN_ENABLE_COMMAND, NULL},
    {HCI_WRITE_SCAN_ENABLE_COMMAND, NULL},
    {HCI_READ_PAGE_SCAN_ACTIVITY_COMMAND, NULL},
    {HCI_WRITE_PAGE_SCAN_ACTIVITY_COMMAND, NULL},
    {HCI_READ_INQUIRY_SCAN_ACTIVITY_COMMAND, NULL},
    {HCI_WRITE_INQUIRY_SCAN_ACTIVITY_COMMAND, NULL},
    {HCI_READ_AUTHENTICATION_ENABLE_COMMAND, NULL},
    {HCI_WRITE_AUTHENTICATION_ENABLE_COMMAND, NULL},
    {HCI_READ_CLASS_OF_DEVICE_COMMAND, NULL},
    {HCI_WRITE_CLASS_OF_DEVICE_COMMAND, NULL},
    {HCI_READ_VOICE_SETTING_COMMAND, NULL},
    {HCI_WRITE_VOICE_SETTING_COMMAND, NULL},
    {HCI_READ_AUTOMATIC_FLUSH_TIMEOUT_COMMAND, NULL},
    {HCI_WRITE_AUTOMATIC_FLUSH_TIMEOUT_COMMAND, NULL},
    {HCI_READ_NUM_BROADCAST_RETRANSMISSIONS_COMMAND, NULL},
    {HCI_WRITE_NUM_BROADCAST_RETRANSMISSIONS_COMMAND, NULL},
    {HCI_READ_HOLD_MODE_ACTIVITY_COMMAND, NULL},
    {HCI_WRITE_HOLD_MODE_ACTIVITY_COMMAND, NULL},
    {HCI_READ_TRANSMIT_POWER_LEVEL_COMMAND, NULL},
    {HCI_READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND, NULL},
    {HCI_WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND, NULL},
    {HCI_SET_CONTROLLER_TO_HOST_FLOW_CONTROL_COMMAND, NULL},
    {HCI_HOST_BUFFER_SIZE_COMMAND, NULL},
    {HCI_HOST_NUMBER_OF_COMPLETED_PACKETS_COMMAND, NULL},
    {HCI_READ_LINK_SUPERVISION_TIMEOUT_COMMAND, NULL},
    {HCI_WRITE_LINK_SUPERVISION_TIMEOUT_COMMAND, NULL},
    {HCI_READ_NUMBER_OF_SUPPORTED_IAC_COMMAND, NULL},
    {HCI_READ_CURRENT_IAC_LAP_COMMAND, NULL},
    {HCI_WRITE_CURRENT_IAC_LAP_COMMAND, NULL},
    {HCI_SET_AFH_HOST_CHANNEL_CLASSIFICATION_COMMAND, NULL},
    {HCI_READ_INQUIRY_SCAN_TYPE_COMMAND, NULL},
    {HCI_WRITE_INQUIRY_SCAN_TYPE_COMMAND, NULL},
    {HCI_READ_INQUIRY_MODE_COMMAND, NULL},
    {HCI_WRITE_INQUIRY_MODE_COMMAND, NULL},
    {HCI_READ_PAGE_SCAN_TYPE_COMMAND, NULL},
    {HCI_WRITE_PAGE_SCAN_TYPE_COMMAND, NULL},
    {HCI_READ_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND, NULL},
    {HCI_WRITE_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND, NULL},
    {HCI_READ_EXTENDED_INQUIRY_RESPONSE_COMMAND, NULL},
    {HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_COMMAND, NULL},
    {HCI_REFRESH_ENCRYPTION_KEY_COMMAND, NULL},
    {HCI_READ_SIMPLE_PAIRING_MODE_COMMAND, NULL},
    {HCI_WRITE_SIMPLE_PAIRING_MODE_COMMAND, NULL},
    {HCI_READ_LOCAL_OOB_DATA_COMMAND, NULL},
    {HCI_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_COMMAND, NULL},
    {HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_COMMAND, NULL},
    {HCI_SEND_KEYPRESS_NOTIFICATION_COMMAND, NULL},
    {HCI_READ_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND, NULL},
    {HCI_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND, NULL},
    {HCI_ENHANCED_FLUSH_COMMAND, NULL},
    {HCI_SET_EVENT_MASK_PAGE2_COMMAND, NULL},
    {HCI_READ_FLOW_CONTROL_MODE_COMMAND, NULL},
    {HCI_WRITE_FLOW_CONTROL_MODE_COMMAND, NULL},
    {HCI_READ_ENHANCED_TRANSMIT_POWER_LEVEL_COMMAND, NULL},
    {HCI_READ_LE_HOST_SUPPORT_COMMAND, NULL},
    {HCI_WRITE_LE_HOST_SUPPORT_COMMAND, NULL},
    {HCI_SET_MWS_CHANNEL_PARAMETERS_COMMAND, NULL},
    {HCI_SET_EXTERNAL_FRAME_CONFIGURATION_COMMAND, NULL},
    {HCI_SET_MWS_SIGNALING_COMMAND, NULL},
    {HCI_SET_MWS_TRANSPORT_LAYER_COMMAND, NULL},
    {HCI_SET_MWS_SCAN_FREQUENCY_TABLE_COMMAND, NULL},
    {HCI_SET_MWS_PATTERN_CONFIGURATION_COMMAND, NULL},
    {HCI_SET_RESERVED_LT_ADDR_COMMAND, NULL},
    {HCI_DELETE_RESERVED_LT_ADDR_COMMAND, NULL},
    {HCI_SET_CONNECTIONLESS_PERIPHERAL_BROADCAST_DATA_COMMAND, NULL},
    {HCI_READ_SYNCHRONIZATION_TRAIN_PARAMETERS_COMMAND, NULL},
    {HCI_WRITE_SYNCHRONIZATION_TRAIN_PARAMETERS_COMMAND, NULL},
    {HCI_READ_SECURE_CONNECTIONS_HOST_SUPPORT_COMMAND, NULL},
    {HCI_WRITE_SECURE_CONNECTIONS_HOST_SUPPORT_COMMAND, NULL},
    {HCI_READ_AUTHENTICATED_PAYLOAD_TIMEOUT_COMMAND, NULL},
    {HCI_WRITE_AUTHENTICATED_PAYLOAD_TIMEOUT_COMMAND, NULL},
    {HCI_READ_LOCAL_OOB_EXTENDED_DATA_COMMAND, NULL},
    {HCI_READ_EXTENDED_PAGE_TIMEOUT_COMMAND, NULL},
    {HCI_WRITE_EXTENDED_PAGE_TIMEOUT_COMMAND, NULL},
    {HCI_READ_EXTENDED_INQUIRY_LENGTH_COMMAND, NULL},
    {HCI_WRITE_EXTENDED_INQUIRY_LENGTH_COMMAND, NULL},
    {HCI_SET_ECOSYSTEM_BASE_INTERVAL_COMMAND, NULL},
    {HCI_CONFIGURE_DATA_PATH_COMMAND, NULL},
    {HCI_SET_MIN_ENCRYPTION_KEY_SIZE_COMMAND, NULL}
};

static const hci_command_t hci_command_informational_parameters_list[] =
{
    {HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND, NULL},
    {HCI_READ_LOCAL_SUPPORTED_COMMANDS_COMMAND, NULL},
    {HCI_READ_LOCAL_SUPPORTED_FEATURES_COMMAND, NULL},
    {HCI_READ_LOCAL_EXTENDED_FEATURES_COMMAND, NULL},
    {HCI_READ_BUFFER_SIZE_COMMAND, NULL},
    {HCI_READ_BDADDR_COMMAND, NULL},
    {HCI_READ_DATA_BLOCK_SIZE_COMMAND, NULL},
    {HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND, NULL},
    {HCI_READ_LOCAL_SIMPLE_PAIRING_OPTIONS_COMMAND, NULL},
    {HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND_V2, NULL},
    {HCI_READ_LOCAL_SUPPORTED_CODEC_CAPABILITIES_COMMAND, NULL},
    {HCI_READ_LOCAL_SUPPORTED_CONTROLLER_DELAY_COMMAND, NULL}
};

static const hci_command_t hci_command_status_parameters_list[] =
{
    {HCI_READ_FAILED_CONTACT_COUNTER_COMMAND, NULL},
    {HCI_RESET_FAILED_CONTACT_COUNTER_COMMAND, NULL},
    {HCI_READ_LINK_QUALITY_COMMAND, NULL},
    {HCI_READ_RSSI_COMMAND, NULL},
    {HCI_READ_AFH_CHANNEL_MAP_COMMAND, NULL},
    {HCI_READ_CLOCK_COMMAND, NULL},
    {HCI_READ_ENCRYPTION_KE_SIZE_COMMAND, NULL},
    {HCI_GET_MWS_TRANSPORT_LAYER_CONFIGURATION_COMMAND, NULL},
    {HCI_SET_TRIGGERED_CLOCK_CAPTURE_COMMAND, NULL}
};

static const hci_command_t hci_command_testing_list[] =
{
    {HCI_READ_LOOPBACK_MODE_COMMAND, NULL},
    {HCI_WRITE_LOOPBACK_MODE_COMMAND, NULL},
    {HCI_ENABLE_IMPLEMENTATION_UNDER_TEST_MODE_COMMAND, NULL},
    {HCI_WRITE_SIMPLE_PAIRING_DEBUG_MODE_COMMAND, NULL},
    {HCI_WRITE_SECURE_CONNECTIONS_TEST_MODE_COMMAND, NULL}
};

struct _PACKED hci_command_read_local_supported_features_retParam_t
{
	_u8  status;
    _u64 feature;
};
controller_error_code_e hci_read_local_supported_features(_u8* data,_u8 length,bt_hci_event_t** event)
{
	struct hci_command_read_local_supported_features_retParam_t *param = \
    hci_command_complete_event(hciCommandOpcode,sizeof(struct hci_command_read_local_supported_features_retParam_t),event);
	param->status  = (_u8)SUCCESS;;
	param->feature = ll_get_feature();
	return SUCCESS;
}
static const hci_command_t hci_command_le_controller_list[] =
{
    {HCI_LE_SET_EVENT_MASK_COMMAND, NULL},
    {HCI_LE_READ_BUFFER_SIZE_COMMAND, NULL},
    {HCI_LE_READ_BUFFER_SIZE_COMMAND_V2, NULL},
    {HCI_LE_READ_LOCAL_SUPPORTED_FEATURES_PAGE0_COMMAND, hci_read_local_supported_features},
    {HCI_LE_SET_RANDOM_ADDRESS_COMMAND, NULL},
    {HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND, NULL},
    {HCI_LE_READ_ADVERTISING_PHYSICAL_CHANNEL_TX_POWER_COMMAND, NULL},
    {HCI_LE_SET_ADVERTISING_DATA_COMMAND, NULL},
    {HCI_LE_SET_SCAN_RESPONSE_DATA_COMMAND, NULL},
    {HCI_LE_SET_ADVERTISING_ENABLE_COMMAND, NULL},
    {HCI_LE_SET_SCAN_PARAMETERS_COMMAND, NULL},
    {HCI_LE_SET_SCAN_ENABLE_COMMAND, NULL},
    {HCI_LE_CREATE_CONNECTION_COMMAND, NULL},
    {HCI_LE_CREATE_CONNECTION_CANCEL_COMMAND, NULL},
    {HCI_LE_READ_FILTER_ACCEPT_LIST_SIZE_COMMAND, NULL},
    {HCI_LE_CLEAR_FILTER_ACCEPT_LIST_COMMAND, NULL},
    {HCI_LE_ADD_DEVICE_TO_FILTER_ACCEPT_LIST_COMMAND, NULL},
    {HCI_LE_REMOVE_DEVICE_FROM_FILTER_ACCEPT_LIST_COMMAND, NULL},
    {HCI_LE_CONNECTION_UPDATE_COMMAND, NULL},
    {HCI_LE_SET_HOST_CHANNEL_CLASSIFICATION_COMMAND, NULL},
    {HCI_LE_READ_CHANNEL_MAP_COMMAND, NULL},
    {HCI_LE_READ_REMOTE_FEATURES_PAGE0_COMMAND, NULL},
    {HCI_LE_ENCRYPT_COMMAND, NULL},
    {HCI_LE_RAND_COMMAND, NULL},
    {HCI_LE_ENABLE_ENCRYPTION_COMMAND, NULL},
    {HCI_LE_LONG_TERM_KEY_REQUEST_REPLY_COMMAND, NULL},
    {HCI_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY_COMMAND, NULL},
    {HCI_LE_READ_SUPPORTED_STATES_COMMAND, NULL},
    {HCI_LE_RECEIVER_TEST_COMMAND, NULL},
    {HCI_LE_RECEIVER_TEST_COMMAND_V2, NULL},
    {HCI_LE_RECEIVER_TEST_COMMAND_V3, NULL},
    {HCI_LE_TRANSMITTER_TEST_COMMAND, NULL},
    {HCI_LE_TRANSMITTER_TEST_COMMAND_V2, NULL},
    {HCI_LE_TRANSMITTER_TEST_COMMAND_V3, NULL},
    {HCI_LE_TRANSMITTER_TEST_COMMAND_V4, NULL},
    {HCI_LE_TEST_END_COMMAND, NULL},
    {HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY_COMMAND, NULL},
    {HCI_LE_REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY_COMMAND, NULL},
    {HCI_LE_SET_DATA_LENGTH_COMMAND, NULL},
    {HCI_LE_READ_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND, NULL},
    {HCI_LE_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND, NULL},
    {HCI_LE_READ_LOCAL_P256_PUBLIC_KEY_COMMAND, NULL},
    {HCI_LE_GENERATE_DHKEY_CMMMMAND, NULL},
    {HCI_LE_GENERATE_DHKEY_CMMMMAND_V2, NULL},
    {HCI_LE_ADD_DEVICE_TO_RESOLVING_LIST_COMMAND, NULL},
    {HCI_LE_REMOVE_DEVICE_FROM_RESOLVING_LIST_COMMAND, NULL},
    {HCI_LE_CLEAR_RESOLVING_LIST_COMMAND, NULL},
    {HCI_LE_READ_RESOLVING_LIST_SIZE_COMMAND, NULL},
    {HCI_LE_READ_PEER_RESOLVABLE_ADDRESS_COMMAND, NULL},
    {HCI_LE_READ_LOCAL_RESOLVABLE_ADDRESS_COMMAND, NULL},
    {HCI_LE_SET_ADDRESS_RESOLUTION_ENABLE_COMMAND, NULL},
    {HCI_LE_SET_RESOLVABLE_PRIVATE_ADDRESS_TIMEOUT_COMMAND, NULL},
    {HCI_LE_READ_MAXIMUM_DATA_LENGTH_COMMAND, NULL},
    {HCI_LE_READ_PHY_COMMAND, NULL},
    {HCI_LE_SET_DEFAULT_PHY_COMMAND, NULL},
    {HCI_LE_SET_PHY_COMMAND, NULL},
    {HCI_LE_SET_ADVERTISING_SET_RANDOM_ADDRESS_COMMAND, NULL},
    {HCI_LE_SET_EXTENDED_ADVERTISING_PARAMETERS_COMMAND, NULL},
    {HCI_LE_SET_EXTENDED_ADVERTISING_PARAMETERS_COMMAND_V2, NULL},
    {HCI_LE_SET_EXTENDED_ADVERTISING_DATA_COMMAND, NULL},
    {HCI_LE_SET_EXTENDED_SCAN_RESPONSE_DATA_COMMAND, NULL},
    {HCI_LE_SET_EXTENDED_ADVERTISING_ENABLE_COMMAND, NULL},
    {HCI_LE_READ_MAXIMUM_ADVERTISING_DATA_LENGTH_COMMAND, NULL},
    {HCI_LE_READ_NUMBER_OF_SUPPORTED_ADVERTISING_SETS_COMMAND, NULL},
    {HCI_LE_REMOVE_ADVERTISING_SET_COMMAND, NULL},
    {HCI_LE_CLEAR_ADVERTISING_SETS_COMMAND, NULL},
    {HCI_LE_SET_PERIODIC_ADVERTISING_PARAMETERS_COMMAND, NULL},
    {HCI_LE_SET_PERIODIC_ADVERTISING_PARAMETERS_COMMAND_V2, NULL},
    {HCI_LE_SET_PERIODIC_ADVERTISING_DATA_COMMAND, NULL},
    {HCI_LE_SET_PERIODIC_ADVERTISING_ENABLE_COMMAND, NULL},
    {HCI_LE_SET_EXTENDED_SCAN_PARAMETERS_COMMAND, NULL},
    {HCI_LE_SET_EXTENDED_SCAN_ENABLE_COMMAND, NULL},
    {HCI_LE_EXTENDED_CREATE_CONNECTION_COMMAND, NULL},
    {HCI_LE_EXTENDED_CREATE_CONNECTION_COMMAND_V2, NULL},
    {HCI_LE_PERIODIC_ADVERTISING_CREATE_SYNC_COMMAND, NULL},
    {HCI_LE_PERIODIC_ADVERTISING_CREATE_SYNC_CANCEL_COMMAND, NULL},
    {HCI_LE_PERIODIC_ADVERTISING_TERMINATE_SYNC_COMMAND, NULL},
    {HCI_LE_ADD_DEVICE_TO_PERIODIC_ADVERTISER_LIST_COMMAND, NULL},
    {HCI_LE_REMOVE_DEVICE_FROM_PERIODIC_ADVERTISER_LIST_COMMAND, NULL},
    {HCI_LE_CLEAR_PERIODIC_ADVERTISER_LIST_COMMAND, NULL},
    {HCI_LE_READ_PERIODIC_ADVERTISER_LIST_SIZE_COMMAND, NULL},
    {HCI_LE_READ_TRANSMIT_POWER_COMMAND, NULL},
    {HCI_LE_READ_RF_PATH_COMPENSATION_COMMAND, NULL},
    {HCI_LE_WRITE_RF_PATH_COMPENSATION_COMMAND, NULL},
    {HCI_LE_SET_PRIVACY_MODE_COMMAND, NULL},
    {HCI_LE_SET_CONNECTIONLESS_CTE_TRANSMIT_PARAMETERS_COMMAND, NULL},
    {HCI_LE_SET_CONNECTIONLESS_CTE_TRANSMIT_ENABLE_COMMAND, NULL},
    {HCI_LE_SET_CONNECTIONLESS_IQ_SAMPLING_ENABLE_COMMAND, NULL},
    {HCI_LE_SET_CONNECTION_CTE_RECEIVE_PARAMETERS_COMMAND, NULL},
    {HCI_LE_SET_CONNECTION_CTE_TRANSMIT_PARAMETERS_COMMAND, NULL},
    {HCI_LE_CONNECTION_CTE_REQUEST_ENABLE_COMMAND, NULL},
    {HCI_LE_CONNECTION_CTE_RESPONSE_ENABLE_COMMAND, NULL},
    {HCI_LE_READ_ANTENNA_INFORMATION_COMMAND, NULL},
    {HCI_LE_SET_PERIODIC_ADVERTISING_RECEIVE_ENABLE_COMMAND, NULL},
    {HCI_LE_PERIODIC_ADVERTISING_SYNC_TRANSFER_COMMAND, NULL},
    {HCI_LE_PERIODIC_ADVERTISING_SET_INFO_TRANSFER_COMMAND, NULL},
    {HCI_LE_SET_PERIODIC_ADVERTISING_SYNC_TRANSFER_PARAMETERS_COMMAND, NULL},
    {HCI_LE_SET_DEFAULT_PERIODIC_ADVERTISING_SYNC_TRANSFER_PARAMETERS_COMMAND, NULL},
    {HCI_LE_MODIFY_SLEEP_CLOCK_ACCURACY_COMMAND, NULL},
    {HCI_LE_READ_ISO_TX_SYNC_COMMAND, NULL},
    {HCI_LE_SET_CIG_PARAMETERS_COMMAND, NULL},
    {HCI_LE_SET_CIG_PARAMETERS_TEST_COMMAND, NULL},
    {HCI_LE_CREATE_CIS_COMMAND, NULL},
    {HCI_LE_REMOVE_CIG_COMMAND, NULL},
    {HCI_LE_ACCEPT_CIS_REQUEST_COMMAND, NULL},
    {HCI_LE_REJECT_CIS_REQUEST_COMMAND, NULL},
    {HCI_LE_CREATE_BIG_COMMAND, NULL},
    {HCI_LE_CREATE_BIG_TEST_COMMAND, NULL},
    {HCI_LE_TERMINATE_BIG_COMMAND, NULL},
    {HCI_LE_BIG_CREATE_SYNC_COMMAND, NULL},
    {HCI_LE_BIG_TERMINATE_SYNC_COMMAND, NULL},
    {HCI_LE_REQUEST_PEER_SCA_COMMAND, NULL},
    {HCI_LE_SETUP_ISO_DATA_PATH_COMMAND, NULL},
    {HCI_LE_REMOVE_ISO_DATA_PATH_COMMAND, NULL},
    {HCI_LE_ISO_TRANSMIT_TEST_COMMAND, NULL},
    {HCI_LE_ISO_RECEIVE_TEST_COMMAND, NULL},
    {HCI_LE_ISO_READ_TEST_COUNTERS_COMMAND, NULL},
    {HCI_LE_ISO_TEST_END_COMMAND, NULL},
    {HCI_LE_SET_HOST_FEATURE_COMMAND, NULL},
    {HCI_LE_SET_HOST_FEATURE_COMMAND_V2, NULL},
    {HCI_LE_READ_ISO_LINK_QUALITY_COMMAND, NULL},
    {HCI_LE_ENHANCED_READ_TRANSMIT_POWER_LEVEL_COMMAND, NULL},
    {HCI_LE_READ_REMOTE_TRANSMIT_POWER_LEVEL_COMMAND, NULL},
    {HCI_LE_SET_PATH_LOSS_REPORTING_PARAMETERS_COMMAND, NULL},
    {HCI_LE_SET_PATH_LOSS_REPORTING_ENABLE_COMMAND, NULL},
    {HCI_LE_SET_TRANSMIT_POWER_REPORTING_ENABLE_COMMAND, NULL},
    {HCI_LE_SET_DATA_RELATED_ADDRESS_CHANGES_COMMAND, NULL},
    {HCI_LE_SET_DEFAULT_SUBRATE_COMMAND, NULL},
    {HCI_LE_SUBRATE_REQUEST_COMMAND, NULL},
    {HCI_LE_SET_PERIODIC_ADVERTISING_SUBEVENT_DATA_COMMAND, NULL},
    {HCI_LE_SET_PERIODIC_ADVERTISING_RESPONSE_DATA_COMMAND, NULL},
    {HCI_LE_SET_PERIODIC_SYNC_SUBEVENT_COMMAND, NULL},
    {HCI_LE_READ_ALL_LOCAL_SUPPORTED_FEATURES_COMMAND, NULL},
    {HCI_LE_READ_ALL_REMOTE_FEATURES_COMMAND, NULL},
    {HCI_LE_CS_READ_LOCAL_SUPPORTED_CAPABILITIES_COMMAND, NULL},
    {HCI_LE_CS_READ_REMOTE_SUPPORTED_CAPABILITIES_COMMAND, NULL},
    {HCI_LE_CS_WRITE_CACHED_REMOTE_SUPPORTED_CAPABILITIES_COMMAND, NULL},
    {HCI_LE_CS_SECURITY_ENABLE_COMMAND, NULL},
    {HCI_LE_CS_SET_DEFAULT_SETTINGS_COMMAND, NULL},
    {HCI_LE_CS_READ_REMOTE_FAE_TABLE_COMMAND, NULL},
    {HCI_LE_CS_WRITE_CACHED_REMOTE_FAE_TABLE_COMMAND, NULL},
    {HCI_LE_CS_CREATE_CONFIG_COMMAND, NULL},
    {HCI_LE_CS_REMOVE_CONFIG_COMMAND, NULL},
    {HCI_LE_CS_SET_CHANNEL_CLASSIFICATION_COMMAND, NULL},
    {HCI_LE_CS_SET_PROCEDURE_PARAMETERS_COMMAND, NULL},
    {HCI_LE_CS_PROCEDURE_ENABLE_COMMAND, NULL},
    {HCI_LE_CS_TEST_COMMAND, NULL},
    {HCI_LE_CS_TEST_END_COMMAND, NULL},
    {HCI_LE_SET_DECISION_DATA_COMMAND, NULL},
    {HCI_LE_SET_DECISION_INSTRUCTIONS_COMMAND, NULL},
    {HCI_LE_ADD_DEVICE_TO_MONITORED_ADVERTISERS_LIST_COMMAND, NULL},
    {HCI_LE_REMOVE_DEVICE_FROM_MONITORED_ADVERTISERS_LIST_COMMAND, NULL},
    {HCI_LE_CLEAR_MONITORED_ADVERTISERS_LIST_COMMAND, NULL},
    {HCI_LE_ENABLE_MONITORING_ADVERTISERS_COMMAND, NULL},
    {HCI_LE_READ_MONITORED_ADVERTISERS_LIST_SIZE_COMMAND, NULL},
    {HCI_LE_FRAME_SPACE_UPDATE_COMMAND, NULL}
};

static const hci_command_t hci_command_vendor_specific_list[] =
{
    {0, NULL},
};

typedef struct
{
    hci_command_e        command;
	hci_command_t const *pArray;
	_u32                 conut;
}hci_command_array_t;

static const hci_command_array_t hci_cmd_handlers[] =
{
	{HCI_COMMAND_LINK_CONTROL,             hci_command_link_control_list,            HCI_COMMAND_LIST_LENGTH(hci_command_link_control_list)},
	{HCI_COMMAND_LINK_POLICY,              hci_command_link_policy_list,             HCI_COMMAND_LIST_LENGTH(hci_command_link_policy_list)},
	{HCI_COMMAND_CONTROLLER_BASEBAND,      hci_command_controller_baseband_list,     HCI_COMMAND_LIST_LENGTH(hci_command_controller_baseband_list)},
	{HCI_COMMAND_INFORMATIONAL_PARAMETERS, hci_command_informational_parameters_list,HCI_COMMAND_LIST_LENGTH(hci_command_informational_parameters_list)},
	{HCI_COMMAND_STATUS_PARAMETERS,        hci_command_status_parameters_list,       HCI_COMMAND_LIST_LENGTH(hci_command_status_parameters_list)},
	{HCI_COMMAND_TESTING,                  hci_command_testing_list,                 HCI_COMMAND_LIST_LENGTH(hci_command_testing_list)},
	{HCI_COMMAND_LE_CONTROLLER,            hci_command_le_controller_list,           HCI_COMMAND_LIST_LENGTH(hci_command_le_controller_list)},
    {HCI_COMMAND_VENDOR_SPECIFIC,          NULL,                                     0},
};

volatile _u8 AAA_COMMAND_BUFFER[16];
volatile _u8 AAA_COMMAND_i;
volatile _u8 AAA_COMMAND_j;
void hci_command_packet_process(_u8* data)
{
    txMemcpy((_u8*)AAA_COMMAND_BUFFER,data,10);
	bt_hci_command_t* hciCommand = (bt_hci_command_t*)data;
    bt_hci_event_t* event = NULL;
    int status = UNKNOWN_HCI_COMMAND;

    for(_u8 i=0;i<HCI_COMMAND_LENGTH(hci_cmd_handlers);i++)
    {
        if(hci_cmd_handlers[i].command == hciCommand->ogf)
        {
            _u32 listLen = hci_cmd_handlers[i].conut;
            for(_u32 j=0 ;j<listLen;j++)
            {
                if(hci_cmd_handlers[i].pArray[j].ocf == hciCommand->ocf)
                {
                	hciCommandOpcode = hciCommand->opcode;
                	AAA_COMMAND_i = i;
                	AAA_COMMAND_j = j;
                	if(hci_cmd_handlers[i].pArray[j].process!=NULL)
                	{
                		status = hci_cmd_handlers[i].pArray[j].process(hciCommand->data,hciCommand->length,&event);
                	}
                }
            }
        }
    }
    if(status == UNKNOWN_HCI_COMMAND)
    {
        event = hci_command_status_event(hciCommand->opcode,UNKNOWN_HCI_COMMAND);
    }
    if(event!=NULL)
    {
        ble_hci_send_data(BLE_HCI_EVENT_PACKET,(_u8*)event,2+event->length);
    }
}

