
#include"common/txCommon.h"

typedef enum
{
	HCI_COMMAND_LINK_CONTROL             = 0x01,
	HCI_COMMAND_LINK_POLICY              = 0x02,
	HCI_COMMAND_CONTROLLER_BASEBAND      = 0x03,
	HCI_COMMAND_INFORMATIONAL_PARAMETERS = 0x04,
	HCI_COMMAND_STATUS_PARAMETERS        = 0x05,
	HCI_COMMAND_TESTING                  = 0x06,
	HCI_COMMAND_LE_CONTROLLER            = 0x08,
}hci_command_e;

typedef enum
{
	HCI_INQUIRY_COMMAND                                              = 0x01,
	HCI_INQUIRY_CANCEL_COMMAND                                       = 0x02,
	HCI_PERIODIC_INQUIRY_MODE_COMMAND                                = 0x03,  
	HCI_EXIT_PERIODIC_INQUIRY_MODE_COMMAND                           = 0x04,   
	HCI_CREATE_CONNECTION_COMMAND                                    = 0x05,   
	HCI_DISCONNECT_COMMAND                                           = 0x06,   
	HCI_CREATE_CONNECTION_CANCEL_COMMAND                             = 0x08,   
	HCI_ACCEPT_CONNECTION_REQUEST_COMMAND                            = 0x09,   
	HCI_REJECT_CONNECTION_REQUEST_COMMAND                            = 0x0A,   
	HCI_LINK_KEY_REQUEST_REPLY_COMMAND                               = 0x0B,   
	HCI_LINK_KEY_REQUEST_NEGATIVE_REPLY_COMMAND                      = 0x0C,   
	HCI_PIN_CODE_REQUEST_REPLY_COMMAND                               = 0x0D,   
	HCI_PIN_CODE_REQUEST_NEGATIVE_REPLY_COMMAND                      = 0x0E,  
	HCI_CHANGE_CONNECTION_PACKET_TYPE_COMMAND                        = 0x0F,   
	HCI_AUTHENTICATION_REQUESTED_COMMAND                             = 0x11,  
	HCI_SET_CONNECTION_ENCRYPTION_COMMAND                            = 0x13,  
	HCI_CHANGE_CONNECTION_LINK_KEY_COMMAND                           = 0x15,   
	HCI_LINK_KEY_SELECTION_COMMAND                                   = 0x17,
	HCI_REMOTE_NAME_REQUEST_COMMAND                                  = 0x19,
	HCI_READ_REMOTE_SUPPORTED_FEATURES_COMMAND                       = 0x1A,   
	HCI_READ_REMOTE_EXTENDED_FEATURES_COMMAND                        = 0x1C,   
	HCI_READ_REMOTE_VERSION_INFORMATION_COMMAND                      = 0x1D, 
	HCI_READ_CLOCK_OFFSET_COMMAND                                    = 0x1F,   
	HCI_READ_LMP_HANDLE_COMMAND                                      = 0x20,   
	HCI_SETUP_SYNCHRONOUS_CONNECTION_COMMAND                         = 0x28,   
	HCI_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND                = 0x29,
	HCI_REJECT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND                = 0x2A, 
	HCI_IO_CAPABILITY_REQUEST_REPLY_COMMAND                          = 0x2B,   
	HCI_USER_CONFIRMATION_REQUEST_REPLY_COMMAND                      = 0x2C,   
	HCI_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY_COMMAND             = 0x2D, 
	HCI_USER_PASSKEY_REQUEST_REPLY_COMMAND                           = 0x2E,   
	HCI_USER_PASSKEY_REQUEST_NEGATIVE_REPLY_COMMAND                  = 0x2F, 
	HCI_REMOTE_OOB_DATA_REQUEST_REPLY_COMMAND                        = 0x30,   
	HCI_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY_COMMAND               = 0x33, 
	HCI_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY_COMMAND                 = 0x34, 
    HCI_ENHANCED_SETUP_SYNCHRONOUS_CONNECTION_COMMAND                = 0x3D, 
    HCI_ENHANCED_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST_COMMAND       = 0x3E, 
    HCI_TRUNCATED_PAGE_COMMAND                                       = 0x3F,   
    HCI_TRUNCATED_PAGE_CANCEL_COMMAND                                = 0x40,   
    HCI_SET_CONNECTIONLESS_PERIPHERAL_BROADCAST_COMMAND              = 0x41,
	HCI_SET_CONNECTIONLESS_PERIPHERAL_BROADCAST_RECEIVE_COMMAND      = 0x42,
    HCI_START_SYNCHRONIZATION_TRAIN_COMMAND                          = 0x43,   
    HCI_RECEIVE_SYNCHRONIZATION_TRAIN_COMMAND                        = 0x44,   
    HCI_REMOTE_OOB_EXTENSION_DATA_REQUEST_REPLY_COMMAND              = 0x45,   
}hci_command_link_control_e;

typedef enum
{
	HCI_HOLD_MODE_COMMAND                                            = 0x01,
	HCI_SNIFF_MODE_COMMAND                                           = 0x03,
	HCI_EXIT_SNIFF_MODE_COMMAND                                      = 0x04,
	HCI_QOS_SETUP_COMMAND                                            = 0x07,
	HCI_ROLE_DISCOVERY_COMMAND                                       = 0x09,
	HCI_SWITCH_ROLE_COMMAND                                          = 0x0b,
	HCI_READ_LINK_POLICY_SETTINGS_COMMAND                            = 0x0c,
	HCI_WRITE_LINK_POLICY_SETTINGS_COMMAND                           = 0x0d,
	HCI_READ_DEFAULT_LINK_POLICY_SETTINGS_COMMAND                    = 0x0e,
	HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS_COMMAND                   = 0x0f,
	HCI_FLOW_SPECIFICATION_COMMAND                                   = 0x10,
	HCI_SNIFF_SUBRATING_COMMAND                                      = 0x11,
}hci_command_link_policy_e;

typedef enum
{
    HCI_SET_EVENT_MASK_COMMAND                                       = 0x01,
    HCI_RESET_COMMAND                                                = 0x03,
    HCI_SET_EVENT_FILTER_COMMAND                                     = 0x05,
    HCI_FLUSH_COMMAND                                                = 0x08,
    HCI_READ_PIN_TYPE_COMMAND                                        = 0x09,
    HCI_WRITE_PIN_TYPE_COMMAND                                       = 0x0a,
    HCI_READ_STORED_LINK_KEY_COMMAND                                 = 0x0d,
    HCI_WRITE_STORED_LINK_KEY_COMMAND                                = 0x11,
    HCI_DELETE_STORED_LINK_KEY_COMMAND                               = 0x12,
    HCI_WRITE_LOCAL_NAME_COMMAND                                     = 0x13,
    HCI_READ_LOCAL_NAME_COMMAND                                      = 0x14,
    HCI_READ_CONNECTION_ACCEPT_TIMEOUT_COMMAND                       = 0x15,
    HCI_WRITE_CONNECTION_ACCEPT_TIMEOUT_COMMAND                      = 0x16,
    HCI_READ_PAGE_TIMEOUT_COMMAND                                    = 0x17,
    HCI_WRITE_PAGE_TIMEOUT_COMMAND                                   = 0x18,
    HCI_READ_SCAN_ENABLE_COMMAND                                     = 0x19,
    HCI_WRITE_SCAN_ENABLE_COMMAND                                    = 0x1a,
    HCI_READ_PAGE_SCAN_ACTIVITY_COMMAND                              = 0x1b,
    HCI_WRITE_PAGE_SCAN_ACTIVITY_COMMAND                             = 0x1c,
    HCI_READ_INQUIRY_SCAN_ACTIVITY_COMMAND                           = 0x1d,
    HCI_WRITE_INQUIRY_SCAN_ACTIVITY_COMMAND                          = 0x1e,
    HCI_READ_AUTHENTICATION_ENABLE_COMMAND                           = 0x1f,
    HCI_WRITE_AUTHENTICATION_ENABLE_COMMAND                          = 0x20,
    HCI_READ_CLASS_OF_DEVICE_COMMAND                                 = 0x23,
    HCI_WRITE_CLASS_OF_DEVICE_COMMAND                                = 0x24,
    HCI_READ_VOICE_SETTING_COMMAND                                   = 0x25,
    HCI_WRITE_VOICE_SETTING_COMMAND                                  = 0x26,
    HCI_READ_AUTOMATIC_FLUSH_TIMEOUT_COMMAND                         = 0x27,
    HCI_WRITE_AUTOMATIC_FLUSH_TIMEOUT_COMMAND                        = 0x28,
    HCI_READ_NUM_BROADCAST_RETRANSMISSIONS_COMMAND                   = 0x29,
    HCI_WRITE_NUM_BROADCAST_RETRANSMISSIONS_COMMAND                  = 0x2a,
    HCI_READ_HOLD_MODE_ACTIVITY_COMMAND                              = 0x2b,
    HCI_WRITE_HOLD_MODE_ACTIVITY_COMMAND                             = 0x2c,
    HCI_READ_TRANSMIT_POWER_LEVEL_COMMAND                            = 0x2d,
    HCI_READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND                 = 0x2e,
    HCI_WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE_COMMAND                = 0x2f,
    HCI_SET_CONTROLLER_TO_HOST_FLOW_CONTROL_COMMAND                  = 0x31,
    HCI_HOST_BUFFER_SIZE_COMMAND                                     = 0x33,
    HCI_HOST_NUMBER_OF_COMPLETED_PACKETS_COMMAND                     = 0x35,
    HCI_READ_LINK_SUPERVISION_TIMEOUT_COMMAND                        = 0x36,
    HCI_WRITE_LINK_SUPERVISION_TIMEOUT_COMMAND                       = 0x37,
    HCI_READ_NUMBER_OF_SUPPORTED_IAC_COMMAND                         = 0x38,
    HCI_READ_CURRENT_IAC_LAP_COMMAND                                 = 0x39,
    HCI_WRITE_CURRENT_IAC_LAP_COMMAND                                = 0x3a,
    HCI_SET_AFH_HOST_CHANNEL_CLASSIFICATION_COMMAND                  = 0x3f,
    HCI_READ_INQUIRY_SCAN_TYPE_COMMAND                               = 0x42,
    HCI_WRITE_INQUIRY_SCAN_TYPE_COMMAND                              = 0x43,
    HCI_READ_INQUIRY_MODE_COMMAND                                    = 0x44,
    HCI_WRITE_INQUIRY_MODE_COMMAND                                   = 0x45,
    HCI_READ_PAGE_SCAN_TYPE_COMMAND                                  = 0x46,
    HCI_WRITE_PAGE_SCAN_TYPE_COMMAND                                 = 0x47,
    HCI_READ_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND                     = 0x48,
    HCI_WRITE_AFH_CHANNEL_ASSESSMENT_MODE_COMMAND                    = 0x49,
    HCI_READ_EXTENDED_INQUIRY_RESPONSE_COMMAND                       = 0x51,
    HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_COMMAND                      = 0x52,
    HCI_REFRESH_ENCRYPTION_KEY_COMMAND                               = 0x53,
    HCI_READ_SIMPLE_PAIRING_MODE_COMMAND                             = 0x55,
    HCI_WRITE_SIMPLE_PAIRING_MODE_COMMAND                            = 0x56,
    HCI_READ_LOCAL_OOB_DATA_COMMAND                                  = 0x57,
    HCI_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL_COMMAND           = 0x58,
	HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_COMMAND                   = 0x59,
	HCI_SEND_KEYPRESS_NOTIFICATION_COMMAND                           = 0x60,
	HCI_READ_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND                = 0x5a,
	HCI_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING_COMMAND               = 0x5b,
	HCI_ENHANCED_FLUSH_COMMAND                                       = 0x5f,
    HCI_SET_EVENT_MASK_PAGE2_COMMAND                                 = 0x63,
    HCI_READ_FLOW_CONTROL_MODE_COMMAND                               = 0x66,
    HCI_WRITE_FLOW_CONTROL_MODE_COMMAND                              = 0x67,
    HCI_READ_ENHANCED_TRANSMIT_POWER_LEVEL_COMMAND                   = 0x68,
    HCI_READ_LE_HOST_SUPPORT_COMMAND                                 = 0x6c,
    HCI_WRITE_LE_HOST_SUPPORT_COMMAND                                = 0x6d,
    HCI_SET_MWS_CHANNEL_PARAMETERS_COMMAND                           = 0x6e,
    HCI_SET_EXTERNAL_FRAME_CONFIGURATION_COMMAND                     = 0x6f,
    HCI_SET_MWS_SIGNALING_COMMAND                                    = 0x70,
    HCI_SET_MWS_TRANSPORT_LAYER_COMMAND                              = 0x71,
    HCI_SET_MWS_SCAN_FREQUENCY_TABLE_COMMAND                         = 0x72,
    HCI_SET_MWS_PATTERN_CONFIGURATION_COMMAND                        = 0x73,
    HCI_SET_RESERVED_LT_ADDR_COMMAND                                 = 0x74,
    HCI_DELETE_RESERVED_LT_ADDR_COMMAND                              = 0x75,
    HCI_SET_CONNECTIONLESS_PERIPHERAL_BROADCAST_DATA_COMMAND         = 0x76,
    HCI_READ_SYNCHRONIZATION_TRAIN_PARAMETERS_COMMAND                = 0x77,
    HCI_WRITE_SYNCHRONIZATION_TRAIN_PARAMETERS_COMMAND               = 0x78,
    HCI_READ_SECURE_CONNECTIONS_HOST_SUPPORT_COMMAND                 = 0x79,
    HCI_WRITE_SECURE_CONNECTIONS_HOST_SUPPORT_COMMAND                = 0x7A,
    HCI_READ_AUTHENTICATED_PAYLOAD_TIMEOUT_COMMAND                   = 0x7B,
    HCI_WRITE_AUTHENTICATED_PAYLOAD_TIMEOUT_COMMAND                  = 0x7C,
    HCI_READ_LOCAL_OOB_EXTENDED_DATA_COMMAND                         = 0x7D,
    HCI_READ_EXTENDED_PAGE_TIMEOUT_COMMAND                           = 0x7E,
    HCI_WRITE_EXTENDED_PAGE_TIMEOUT_COMMAND                          = 0x7F,
    HCI_READ_EXTENDED_INQUIRY_LENGTH_COMMAND                         = 0x80,
    HCI_WRITE_EXTENDED_INQUIRY_LENGTH_COMMAND                        = 0x81,
    HCI_SET_ECOSYSTEM_BASE_INTERVAL_COMMAND                          = 0x82,
    HCI_CONFIGURE_DATA_PATH_COMMAND                                  = 0x83,
    HCI_SET_MIN_ENCRYPTION_KEY_SIZE_COMMAND                          = 0x84,
}hci_command_controller_baseband_e;

typedef enum
{
	HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND                       = 0x01,
    HCI_READ_LOCAL_SUPPORTED_COMMANDS_COMMAND                        = 0x02,
    HCI_READ_LOCAL_SUPPORTED_FEATURES_COMMAND                        = 0x03,
    HCI_READ_LOCAL_EXTENDED_FEATURES_COMMAND                         = 0x04,
    HCI_READ_BUFFER_SIZE_COMMAND                                     = 0x05,
    HCI_READ_BDADDR_COMMAND                                          = 0x09,
    HCI_READ_DATA_BLOCK_SIZE_COMMAND                                 = 0x0a,
    HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND                          = 0x0b,
	HCI_READ_LOCAL_SUPPORTED_CODECS_COMMAND_V2                       = 0x0d,
    HCI_READ_LOCAL_SIMPLE_PAIRING_OPTIONS_COMMAND                    = 0x0c,
    HCI_READ_LOCAL_SUPPORTED_CODEC_CAPABILITIES_COMMAND              = 0x0e,
    HCI_READ_LOCAL_SUPPORTED_CONTROLLER_DELAY_COMMAND                = 0x0f,
}hci_command_informational_parameters_e;


typedef enum {
    HCI_READ_FAILED_CONTACT_COUNTER_COMMAND              = 0x01,
    HCI_RESET_FAILED_CONTACT_COUNTER_COMMAND             = 0x02,
    HCI_READ_LINK_QUALITY_COMMAND                        = 0x03,
    HCI_READ_RSSI_COMMAND                                = 0x05,
    HCI_READ_AFH_CHANNEL_MAP_COMMAND                     = 0x06,
    HCI_READ_CLOCK_COMMAND                               = 0x07,
    HCI_READ_ENCRYPTION_KE_SIZE_COMMAND                  = 0x08,
    HCI_GET_MWS_TRANSPORT_LAYER_CONFIGURATION_COMMAND    = 0x0C,
    HCI_SET_TRIGGERED_CLOCK_CAPTURE_COMMAND              = 0x0D,
} hci_command_status_parameters_e;

typedef enum{
	HCI_READ_LOOPBACK_MODE_COMMAND                       = 0x01,
	HCI_WRITE_LOOPBACK_MODE_COMMAND                      = 0x02,
	HCI_ENABLE_IMPLEMENTATION_UNDER_TEST_MODE_COMMAND    = 0x03,
	HCI_WRITE_SIMPLE_PAIRING_DEBUG_MODE_COMMAND          = 0x04,
	HCI_WRITE_SECURE_CONNECTIONS_TEST_MODE_COMMAND       = 0x0a,
}hci_command_testing_e


typedef enum
{

}hci_command_le_controller_e;

void hci_command_packet_process(_u8* data);
