#include"common/txCommon.h"

 #ifndef LL_H_
 #define LL_H_

/***********************Bluetooth LE Controller code**************************/
typedef enum
{
    SUCCESS                                           = 0x00,
    UNKNOWN_HCI_COMMAND                               = 0x01,
    UNKNOWN_CONNECTION_IDENTIFIER                     = 0x02,
    HARDWARE_FAILURE                                  = 0x03,
    PAGE_TIMEOUT                                      = 0x04,
    AUTHENTICATION_FAILURE                            = 0x05,
    PIN_OR_KEY_MISSING                                = 0x06,
    MEMORY_CAPACITY_EXCEEDED                          = 0x07,
    CONNECTION_TIMEOUT                                = 0x08,
    CONNECTION_LIMIT_EXCEEDED                         = 0x09,
    SYNCHRONOUS_CONNECTION_LIMIT_TO_A_DEVICE_EXCEEDED = 0x0A,
    CONNECTION_ALREADY_EXISTS                         = 0x0B,
    COMMAND_DISALLOWED                                = 0x0C,
    CONNECTION_REJECTED_DUE_TO_LIMITED_RESOURCES      = 0x0D,
    CONNECTION_REJECTED_DUE_TO_SECURITY_REASONS       = 0x0E,
    CONNECTION_REJECTED_DUE_TO_UNACCEPTABLE_BD_ADDR   = 0x0F,
    CONNECTION_ACCEPT_TIMEOUT_EXCEEDED                = 0x10,
    UNSUPPORTED_FEATURE_OR_PARAMETER_VALUE            = 0x11,
    IVALID_HCI_COMMAND_PARAMETERS                     = 0x12,
    REMOTE_USER_TERMINATED_CONNNECTION                = 0x13,
    REMOTE_DEVICE_TERMINATED_DUE_TO_LOW_RESOURCES     = 0x14,
    REMOTE_DEVICE_TERMINATED_DUE_TO_POWER_OFF         = 0x15,
    CONNECTION_TERMINATED_BY_LOCAL_HOST               = 0x16,
    REPEATED_ATTEMPTS                                 = 0x17,
    PAIRING_NOT_ALLOWED                               = 0x18,
    UNKNOWN_LMP_PDU                                   = 0x19,
    UNSUPPORTED_REMOTE_FEATURE                        = 0x1A,
    SCO_OFFSET_REJECTED                               = 0x1B,
    SCO_INTERVAL_REJECTED                             = 0x1C,
    SCO_AIR_MODE_REJECTED                             = 0x1D,
    INVALID_LL_PARAMETERS                             = 0x1E,
    UNSPECIFIED_ERROR                                 = 0x1F,
    UNSUPPORTED_LL_PARAMETER_VALUE                    = 0x20,
    ROLE_CHANGE_NOT_ALLOWED                           = 0x21,
    LL_RESPONSE_TIMEOUT                               = 0x22,
    LL_PROCEDURE_COLLISION                            = 0x23,
    LMP_PDU_NOT_ALLOWED                               = 0x24,
    ENCRYPTION_MODE_NOT_ACCEPTABLE                    = 0x25,
    LINK_KEY_CANNOT_BE_CHANGED                        = 0x26,
    REQUESTED_QOS_NOT_SUPPORTED                       = 0x27,
    INSTANT_PASSED                                    = 0x28,
    PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED               = 0x29,
    DIFFERENT_TRANSACTION_COLLISION                   = 0x2A,
    RESERVED_FOR_FUTURE_USE_0                         = 0x2B,
    QOS_UNACCEPTABLE_PARAMETER                        = 0x2C,
    QOS_REJECTED                                      = 0x2D,
    CHANNEL_CLASSIFICATION_NOT_SUPPORTED              = 0x2E,
    INSUFFICIENT_SECURITY                             = 0x2F,
    PARAMETER_OUT_OF_MANDATORY_RANGE                  = 0x30,
    RESERVED_FOR_FUTURE_USE_1                         = 0x31,
    ROLE_SWITCH_PENDING                               = 0x32,
    RESERVED_FOR_FUTURE_USE_2                         = 0x33,
    RESERVED_SLOT_VIOLATION                           = 0x34,
    ROLE_SWITCH_FAILED                                = 0x35,
    EXTENDED_INQUIRY_RESPONSE_TOO_LARGE               = 0x36,
    SECURE_SIMPLE_PAIRING_NOT_SUPPORTED_BY_HOST       = 0x37,
    HOST_BUSY_PAIRING                                 = 0x38,
    CONNECTION_REJECTED_DUE_TO_NO_SUITABLE_CHANNEL    = 0x39,
    CONTROLLER_BUSY                                   = 0x3A,
    UNACCEPTABLE_CONNECTION_PARAMETERS                = 0x3B,
    ADVERTISING_TIMEOUT                               = 0x3C,
    CONNECTION_TERMINATED_DUE_TO_MIC_FAILURE          = 0x3D,
    CONNECTION_FAILED_TO_ESTABLISHED                  = 0x3E,
    PREVIOUSLY_USED                                   = 0x3F,
    COARSE_CLOCK_ADJUSTMENT_REJECTED_TRY_TO_ADJIUT    = 0x40,
    TYPE0_SUBMAP_NOT_DEFINED                          = 0x41,
    UNKNOWN_ADVERTISING_IDENTIFIER                    = 0x42,
    LIMIT_REACHED                                     = 0x43,
    OPERATION_CANCELLED_BY_HOST                       = 0x44,
    PACKET_TOO_LONG                                   = 0x45,
    TOO_LATE                                          = 0x46,
    TOO_EARLY                                         = 0x47,
    INSUFFICIENT_CHANNELS                             = 0x48,
}controller_error_code_e;

/***********************Bluetooth LE Feature define**************************/

#define LL_FEATURE_BIT_LE_ENCRYPTION                              BIT(0)
#define LL_FEATURE_BIT_CONNECTION_PARAMETERS_REQUEST              BIT(1)
#define LL_FEATURE_BIT_EXTENDED_REJECT                            BIT(2)
#define LL_FEATURE_BIT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE     BIT(3)
#define LL_FEATURE_BIT_LE_PING                                    BIT(4)
#define LL_FEATURE_BIT_LE_DATA_PACKET_LENGTH_EXTENSION            BIT(5)
#define LL_FEATURE_BIT_LL_PRIVACY                                 BIT(6)
#define LL_FEATURE_BIT_EXTENDED_SCANNING_FILTER_POLICIES          BIT(7)
#define LL_FEATURE_BIT_LE_2M_PHY                                  BIT(8)
#define LL_FEATURE_BIT_STABLE_MODULATION_INDEX_TX                 BIT(9)
#define LL_FEATURE_BIT_STABLE_MODULATION_INDEX_RX                 BIT(10)
#define LL_FEATURE_BIT_LE_CODED_PHY                               BIT(11)
#define LL_FEATURE_BIT_LE_EXTENDED_ADVERTISING                    BIT(12)
#define LL_FEATURE_BIT_LE_PERIODIC_ADVERTISING                    BIT(13)
#define LL_FEATURE_BIT_CHANNEL_SELECTION_ALGORITHM_2              BIT(14)
#define LL_FEATURE_BIT_LE_POWER_CLASS_1                           BIT(15)
#define LL_FEATURE_BIT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE  BIT(16)
#define LL_FEATURE_BIT_CONNECTION_CTE_REQUEST                     BIT(17)
#define LL_FEATURE_BIT_CONNECTION_CTE_RESPONSE                    BIT(18)
#define LL_FEATURE_BIT_CONNECTIONLESS_CTE_TRANSMITTER             BIT(19)
#define LL_FEATURE_BIT_CONNECTIONLESS_CTE_RECEIVER                BIT(20)
#define LL_FEATURE_BIT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION  BIT(21)
#define LL_FEATURE_BIT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION     BIT(22)
#define LL_FEATURE_BIT_RECEIVING_CONSTANT_TONE_EXTENSIONS         BIT(23)
#define LL_FEATURE_BIT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER  BIT(24)
#define LL_FEATURE_BIT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT BIT(25)
#define LL_FEATURE_BIT_SLEEP_CLOCK_ACCURACY_UPDATES               BIT(26)
#define LL_FEATURE_BIT_REMOTE_PUBLIC_KEY_VALIDATION               BIT(27)
#define LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL       BIT(28)
#define LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL    BIT(29)
#define LL_FEATURE_BIT_ISOCHRONOUS_BROADCASTER                    BIT(30)
#define LL_FEATURE_BIT_SYNCHRONIZED_RECEIVER                      BIT(31)
#define LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT  BIT(32)
#define LL_FEATURE_BIT_LE_POWER_CONTROL_REQUEST                   BIT(33)
#define LL_FEATURE_BIT_LE_POWER_CONTROL_REQUEST1                  BIT(34)
#define LL_FEATURE_BIT_LE_PATH_LOSS_MONITORING                    BIT(35)
#define LL_FEATURE_BIT_PERIODIC_ADVERTISING_ADI_SUPPORT           BIT(36)
#define LL_FEATURE_BIT_CONNECTION_SUBRATING                       BIT(37)
#define LL_FEATURE_BIT_CONNECTION_SUBRATING_HOST_SUPPORT          BIT(38)
#define LL_FEATURE_BIT_CHANNEL_CLASSIFICATION                     BIT(39)
#define LL_FEATURE_BIT_ADVERTISING_CODING_SELECTION               BIT(40)
#define LL_FEATURE_BIT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT  BIT(41)
#define LL_FEATURE_BIT_DECISION_BASED_ADVERTISING_FILTERING       BIT(42)
#define LL_FEATURE_BIT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER  BIT(43)
#define LL_FEATURE_BIT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER    BIT(44)
#define LL_FEATURE_BIT_UNSEGMENTED_FRAMED_MODE                    BIT(45)
#define LL_FEATURE_BIT_CHANNEL_SOUNDING                           BIT(46)
#define LL_FEATURE_BIT_CHANNEL_SOUNDING_HOST_SUPPORT              BIT(47)
#define LL_FEATURE_BIT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION   BIT(48)
//reserved for specification developments purposes
#define LL_FEATURE_BIT_LE_EXTENDED_FEATURE_SET                    BIT(63)
#define LL_FEATURE_BIT_MONITORING_ADVERTISERS                     BIT(64)
#define LL_FEATURE_BIT_FRAME_SPACE_UPDATE                         BIT(65)

/***********************Bluetooth LE Supported Feature **************************/
#define LL_HOST_CONTROLLED_FEATURE  (\
		LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT|\
		LL_FEATURE_BIT_CONNECTION_SUBRATING_HOST_SUPPORT|\
		LL_FEATURE_BIT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT|\
		LL_FEATURE_BIT_CHANNEL_SOUNDING_HOST_SUPPORT)




/***********************Bluetooth LE Supported Feature **************************/
#ifdef LL_SUPPORT_LE_ENCRYPTION
#undef LL_SUPPORT_LE_ENCRYPTION
#define LL_SUPPORT_LE_ENCRYPTION LL_FEATURE_BIT_LE_ENCRYPTION
#else
#define LL_SUPPORT_LE_ENCRYPTION 0
#endif

#ifdef LL_SUPPORT_CONNECTION_PARAMETERS_REQUEST
#undef LL_SUPPORT_CONNECTION_PARAMETERS_REQUEST
#define LL_SUPPORT_CONNECTION_PARAMETERS_REQUEST LL_FEATURE_BIT_CONNECTION_PARAMETERS_REQUEST
#else
#define LL_SUPPORT_CONNECTION_PARAMETERS_REQUEST 0
#endif

#ifdef LL_SUPPORT_EXTENDED_REJECT
#undef LL_SUPPORT_EXTENDED_REJECT
#define LL_SUPPORT_EXTENDED_REJECT LL_FEATURE_BIT_EXTENDED_REJECT
#else
#define LL_SUPPORT_EXTENDED_REJECT 0
#endif

#ifdef LL_SUPPORT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE
#undef LL_SUPPORT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE
#define LL_SUPPORT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE LL_FEATURE_BIT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE
#else
#define LL_SUPPORT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE 0
#endif

#ifdef LL_SUPPORT_LE_PING
#undef LL_SUPPORT_LE_PING
#define LL_SUPPORT_LE_PING LL_FEATURE_BIT_LE_PING
#else
#define LL_SUPPORT_LE_PING 0
#endif

#ifdef LL_SUPPORT_LE_DATA_PACKET_LENGTH_EXTENSION
#undef LL_SUPPORT_LE_DATA_PACKET_LENGTH_EXTENSION
#define LL_SUPPORT_LE_DATA_PACKET_LENGTH_EXTENSION LL_FEATURE_BIT_LE_DATA_PACKET_LENGTH_EXTENSION
#else
#define LL_SUPPORT_LE_DATA_PACKET_LENGTH_EXTENSION 0
#endif

#ifdef LL_SUPPORT_LL_PRIVACY
#undef LL_SUPPORT_LL_PRIVACY
#define LL_SUPPORT_LL_PRIVACY LL_FEATURE_BIT_LL_PRIVACY
#else
#define LL_SUPPORT_LL_PRIVACY 0
#endif

#ifdef LL_SUPPORT_EXTENDED_SCANNING_FILTER_POLICIES
#undef LL_SUPPORT_EXTENDED_SCANNING_FILTER_POLICIES
#define LL_SUPPORT_EXTENDED_SCANNING_FILTER_POLICIES LL_FEATURE_BIT_EXTENDED_SCANNING_FILTER_POLICIES
#else
#define LL_SUPPORT_EXTENDED_SCANNING_FILTER_POLICIES 0
#endif

#ifdef LL_SUPPORT_LE_2M_PHY
#undef LL_SUPPORT_LE_2M_PHY
#define LL_SUPPORT_LE_2M_PHY LL_FEATURE_BIT_LE_2M_PHY
#else
#define LL_SUPPORT_LE_2M_PHY 0
#endif

#ifdef LL_SUPPORT_STABLE_MODULATION_INDEX_TX
#undef LL_SUPPORT_STABLE_MODULATION_INDEX_TX
#define LL_SUPPORT_STABLE_MODULATION_INDEX_TX LL_FEATURE_BIT_STABLE_MODULATION_INDEX_TX
#else
#define LL_SUPPORT_STABLE_MODULATION_INDEX_TX 0
#endif

#ifdef LL_SUPPORT_STABLE_MODULATION_INDEX_RX
#undef LL_SUPPORT_STABLE_MODULATION_INDEX_RX
#define LL_SUPPORT_STABLE_MODULATION_INDEX_RX LL_FEATURE_BIT_STABLE_MODULATION_INDEX_RX
#else
#define LL_SUPPORT_STABLE_MODULATION_INDEX_RX 0
#endif

#ifdef LL_SUPPORT_LE_CODED_PHY
#undef LL_SUPPORT_LE_CODED_PHY
#define LL_SUPPORT_LE_CODED_PHY LL_FEATURE_BIT_LE_CODED_PHY
#else
#define LL_SUPPORT_LE_CODED_PHY 0
#endif

#ifdef LL_SUPPORT_LE_EXTENDED_ADVERTISING
#undef LL_SUPPORT_LE_EXTENDED_ADVERTISING
#define LL_SUPPORT_LE EXTENDED_ADVERTISING LL_FEATURE_BIT_LE_EXTENDED_ADVERTISING
#else
#define LL_SUPPORT_LE_EXTENDED_ADVERTISING 0
#endif

#ifdef LL_SUPPORT_LE_PERIODIC_ADVERTISING
#undef LL_SUPPORT_LE_PERIODIC_ADVERTISING
#define LL_SUPPORT_LE_PERIODIC_ADVERTISING LL_FEATURE_BIT_LE_PERIODIC_ADVERTISING
#else
#define LL_SUPPORT_LE_PERIODIC_ADVERTISING 0
#endif

#ifdef LL_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2
#undef LL_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2
#define LL_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2 LL_FEATURE_BIT_CHANNEL_SELECTION_ALGORITHM_2
#else
#define LL_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2 0
#endif

#ifdef LL_SUPPORT_LE_POWER_CLASS_1
#undef LL_SUPPORT_LE_POWER_CLASS_1
#define LL_SUPPORT_LE_POWER_CLASS_1 LL_FEATURE_BIT_LE_POWER_CLASS_1
#else
#define LL_SUPPORT_LE_POWER_CLASS_1 0
#endif

#ifdef LL_SUPPORT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE
#undef LL_SUPPORT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE
#define LL_SUPPORT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE LL_FEATURE_BIT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE
#else
#define LL_SUPPORT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE 0
#endif

#ifdef LL_SUPPORT_CONNECTION_CTE_REQUEST
#undef LL_SUPPORT_CONNECTION_CTE_REQUEST
#define LL_SUPPORT_CONNECTION_CTE_REQUEST LL_FEATURE_BIT_CONNECTION_CTE_REQUEST
#else
#define LL_SUPPORT_CONNECTION_CTE_REQUEST 0
#endif

#ifdef LL_SUPPORT_CONNECTION_CTE_RESPONSE
#undef LL_SUPPORT_CONNECTION_CTE_RESPONSE
#define LL_SUPPORT_CONNECTION_CTE_RESPONSE LL_FEATURE_BIT_CONNECTION_CTE_RESPONSE
#else
#define LL_SUPPORT_CONNECTION_CTE_RESPONSE 0
#endif

#ifdef LL_SUPPORT_CONNECTIONLESS_CTE_TRANSMITTER
#undef LL_SUPPORT_CONNECTIONLESS_CTE_TRANSMITTER
#define LL_SUPPORT_CONNECTIONLESS_CTE_TRANMSITTER LL_FEATURE_BIT_CONNECTIONLESS_CTE_TRANSMITTER
#else
#define LL_SUPPORT_CONNECTIONLESS_CTE_TRANSMITTER 0
#endif

#ifdef LL_SUPPORT_CONNECTIONLESS_CTE_RECEIVER
#undef LL_SUPPORT_CONNECTIONLESS_CTE_RECEIVER
#define LL_SUPPORT_CONNECTIONLESS_CTE_RECEIVER LL_FEATURE_BIT_CONNECTIONLESS_CTE_RECEIVER
#else
#define LL_SUPPORT_CONNECTIONLESS_CTE_RECEIVER 0
#endif

#ifdef LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION
#undef LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION
#define LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION LL_FEATURE_BIT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION
#else
#define LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION 0
#endif

#ifdef LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION
#undef LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION
#define LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION LL_FEATURE_BIT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION
#else
#define LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION 0
#endif

#ifdef LL_SUPPORT_RECEIVING_CONSTANT_TONE_EXTENSIONS
#undef LL_SUPPORT_RECEIVING_CONSTANT_TONE_EXTENSIONS
#define LL_SUPPORT_RECEIVING_CONSTANT_TONE_EXTENSIONS LL_FEATURE_BIT_RECEIVING_CONSTANT_TONE_EXTENSIONS
#else
#define LL_SUPPORT_RECEIVING_CONSTANT_TONE_EXTENSIONS 0
#endif

#ifdef LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER
#undef LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER
#define LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER LL_FEATURE_BIT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER
#else
#define LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER 0
#endif

#ifdef LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT
#undef LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT
#define LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT LL_FEATURE_BIT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT
#else
#define LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT 0
#endif

#ifdef LL_SUPPORT_SLEEP_CLOCK_ACCURACY_UPDATES
#undef LL_SUPPORT_SLEEP_CLOCK_ACCURACY_UPDATES
#define LL_SUPPORT_SLEEP_CLOCK_ACCURACY_UPDATES LL_FEATURE_BIT_SLEEP_CLOCK_ACCURACY_UPDATES
#else
#define LL_SUPPORT_SLEEP_CLOCK_ACCURACY_UPDATES 0
#endif

#ifdef LL_SUPPORT_REMOTE_PUBLIC_KEY_VALIDATION
#undef LL_SUPPORT_REMOTE_PUBLIC_KEY_VALIDATION
#define LL_SUPPORT_REMOTE_PUBLIC_KEY_VALIDATION LL_FEATURE_BIT_REMOTE_PUBLIC_KEY_VALIDATION
#else
#define LL_SUPPORT_REMOTE_PUBLIC_KEY_VALIDATION 0
#endif

#ifdef LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL
#undef LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL
#else
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL 0
#endif

#ifdef LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL
#undef LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL
#else
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL 0
#endif

#ifdef LL_SUPPORT_ISOCHRONOUS_BROADCASTER
#undef LL_SUPPORT_ISOCHRONOUS_BROADCASTER
#define LL_SUPPORT_ISOCHRONOUS_BROADCASTER LL_FEATURE_BIT_ISOCHRONOUS_BROADCASTER
#else
#define LL_SUPPORT_ISOCHRONOUS_BROADCASTER 0
#endif

#ifdef LL_SUPPORT_SYNCHRONIZED_RECEIVER
#undef LL_SUPPORT_SYNCHRONIZED_RECEIVER
#define LL_SUPPORT_SYNCHRONIZED_RECEIVER LL_FEATURE_BIT_SYNCHRONIZED_RECEIVER
#else
#define LL_SUPPORT_SYNCHRONIZED_RECEIVER 0
#endif

#ifdef LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT
#undef LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT
#else
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT 0
#endif

#ifdef LL_SUPPORT_LE_POWER_CONTROL_REQUEST
#undef LL_SUPPORT_LE_POWER_CONTROL_REQUEST
#define LL_SUPPORT_LE_POWER_CONTROL_REQUEST LL_FEATURE_BIT_LE_POWER_CONTROL_REQUEST
#else
#define LL_SUPPORT_LE_POWER_CONTROL_REQUEST 0
#endif

#ifdef LL_SUPPORT_LE_POWER_CONTROL_REQUEST1
#undef LL_SUPPORT_LE_POWER_CONTROL_REQUEST1
#define LL_SUPPORT_LE_POWER_CONTROL_REQUEST1 LL_FEATURE_BIT_LE_POWER_CONTROL_REQUEST1
#else
#define LL_SUPPORT_LE_POWER_CONTROL_REQUEST1 0
#endif

#ifdef LL_SUPPORT_LE_PATH_LOSS_MONITORING
#undef LL_SUPPORT_LE_PATH_LOSS_MONITORING
#define LL_SUPPORT_LE_PATH_LOSS_MONITORING LL_FEATURE_BIT_LE_PATH_LOSS_MONITORING
#else
#define LL_SUPPORT_LE_PATH_LOSS_MONITORING 0
#endif

#ifdef LL_SUPPORT_PERIODIC_ADVERTISING_ADI_SUPPORT
#undef LL_SUPPORT_PERIODIC_ADVERTISING_ADI_SUPPORT
#define LL_SUPPORT_PERIODIC_ADVERTISING_ADI_SUPPORT LL_FEATURE_BIT_PERIODIC_ADVERTISING_ADI_SUPPORT
#else
#define LL_SUPPORT_PERIODIC_ADVERTISING_ADI_SUPPORT 0
#endif

#ifdef LL_SUPPORT_CONNECTION_SUBRATING
#undef LL_SUPPORT_CONNECTION_SUBRATING
#define LL_SUPPORT_CONNECTION_SUBRATING LL_FEATURE_BIT_CONNECTION_SUBRATING
#else
#define LL_SUPPORT_CONNECTION_SUBRATING 0
#endif

#ifdef LL_SUPPORT_CONNECTION_SUBRATING_HOST_SUPPORT
#undef LL_SUPPORT_CONNECTION_SUBRATING_HOST_SUPPORT
#define LL_SUPPORT_CONNECTION_SUBRATING_HOST_SUPPORT LL_FEATURE_BIT_CONNECTION_SUBRATING_HOST_SUPPORT
#else
#define LL_SUPPORT_CONNECTION_SUBRATING_HOST_SUPPORT 0
#endif

#ifdef LL_SUPPORT_CHANNEL_CLASSIFICATION
#undef LL_SUPPORT_CHANNEL_CLASSIFICATION
#define LL_SUPPORT_CHANNEL_CLASSIFICATION LL_FEATURE_BIT_CHANNEL_CLASSIFICATION
#else
#define LL_SUPPORT_CHANNEL_CLASSIFICATION 0
#endif

#ifdef LL_SUPPORT_ADVERTISING_CODING_SELECTION
#undef LL_SUPPORT_ADVERTISING_CODING_SELECTION
#define LL_SUPPORT_ADVERTISING_CODING_SELECTION LL_FEATURE_BIT_ADVERTISING_CODING_SELECTION
#else
#define LL_SUPPORT_ADVERTISING_CODING_SELECTION 0
#endif

#ifdef LL_SUPPORT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT
#undef LL_SUPPORT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT
#define LL_SUPPORT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT LL_FEATURE_BIT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT
#else
#define LL_SUPPORT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT 0
#endif

#ifdef LL_SUPPORT_DECISION_BASED_ADVERTISING_FILTERING
#undef LL_SUPPORT_DECISION_BASED_ADVERTISING_FILTERING
#define LL_SUPPORT_DECISION_BASED_ADVERTISING_FILTERING LL_FEATURE_BIT_DECISION_BASED_ADVERTISING_FILTERING
#else
#define LL_SUPPORT_DECISION_BASED_ADVERTISING_FILTERING 0
#endif

#ifdef LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER
#undef LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER
#define LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER LL_FEATURE_BIT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER
#else
#define LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER 0
#endif

#ifdef LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER
#undef LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER
#define LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER LL_FEATURE_BIT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER
#else
#define LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER 0
#endif

#ifdef LL_SUPPORT_UNSEGMENTED_FRAMED_MODE
#undef LL_SUPPORT_UNSEGMENTED_FRAMED_MODE
#define LL_SUPPORT_UNSEGMENTED_FRAMED_MODE LL_FEATURE_BIT_UNSEGMENTED_FRAMED_MODE
#else
#define LL_SUPPORT_UNSEGMENTED_FRAMED_MODE 0
#endif

#ifdef LL_SUPPORT_CHANNEL_SOUNDING
#undef LL_SUPPORT_CHANNEL_SOUNDING
#define LL_SUPPORT_CHANNEL_SOUNDING LL_FEATURE_BIT_CHANNEL_SOUNDING
#else
#define LL_SUPPORT_CHANNEL_SOUNDING 0
#endif

#ifdef LL_SUPPORT_CHANNEL_SOUNDING_HOST_SUPPORT
#undef LL_SUPPORT_CHANNEL_SOUNDING_HOST_SUPPORT
#define LL_SUPPORT_CHANNEL_SOUNDING_HOST_SUPPORT LL_FEATURE_BIT_CHANNEL_SOUNDING_HOST_SUPPORT
#else
#define LL_SUPPORT_CHANNEL_SOUNDING_HOST_SUPPORT 0
#endif

#ifdef LL_SUPPORT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION
#undef LL_SUPPORT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION
#define LL_SUPPORT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION LL_FEATURE_BIT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION
#else
#define LL_SUPPORT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION 0
#endif

#ifdef LL_SUPPORT_LE_EXTENDED_FEATURE_SET
#undef LL_SUPPORT_LE_EXTENDED_FEATURE_SET
#define LL_SUPPORT_LE_EXTENDED_FEATURE_SET LL_FEATURE_BIT_LE_EXTENDED_FEATURE_SET
#else
#define LL_SUPPORT_LE_EXTENDED_FEATURE_SET 0
#endif

#ifdef LL_SUPPORT_MONITORING_ADVERTISERS
#undef LL_SUPPORT_MONITORING_ADVERTISERS
#define LL_SUPPORT_MONITORING_ADVERTISERS LL_FEATURE_BIT_MONITORING_ADVERTISERS
#else
#define LL_SUPPORT_MONITORING_ADVERTISERS 0
#endif

#ifdef LL_SUPPORT_FRAME_SPACE_UPDATE
#undef LL_SUPPORT_FRAME_SPACE_UPDATE
#define LL_SUPPORT_FRAME_SPACE_UPDATE LL_FEATURE_BIT_FRAME_SPACE_UPDATE
#else
#define LL_SUPPORT_FRAME_SPACE_UPDATE 0
#endif

#define LL_FEATURE_SUPPORT (\
    LL_SUPPORT_LE_ENCRYPTION | \
    LL_SUPPORT_CONNECTION_PARAMETERS_REQUEST | \
    LL_SUPPORT_EXTENDED_REJECT | \
    LL_SUPPORT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE | \
    LL_SUPPORT_LE_PING | \
    LL_SUPPORT_LE_DATA_PACKET_LENGTH_EXTENSION | \
    LL_SUPPORT_LL_PRIVACY | \
    LL_SUPPORT_EXTENDED_SCANNING_FILTER_POLICIES | \
    LL_SUPPORT_LE_2M_PHY | \
    LL_SUPPORT_STABLE_MODULATION_INDEX_TX | \
    LL_SUPPORT_STABLE_MODULATION_INDEX_RX | \
    LL_SUPPORT_LE_CODED_PHY | \
    LL_SUPPORT_LE_EXTENDED_ADVERTISING | \
    LL_SUPPORT_LE_PERIODIC_ADVERTISING | \
    LL_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2 | \
    LL_SUPPORT_LE_POWER_CLASS_1 | \
    LL_SUPPORT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE | \
    LL_SUPPORT_CONNECTION_CTE_REQUEST | \
    LL_SUPPORT_CONNECTION_CTE_RESPONSE | \
    LL_SUPPORT_CONNECTIONLESS_CTE_TRANSMITTER | \
    LL_SUPPORT_CONNECTIONLESS_CTE_RECEIVER | \
    LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION | \
    LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION | \
    LL_SUPPORT_RECEIVING_CONSTANT_TONE_EXTENSIONS | \
    LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER | \
    LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT | \
    LL_SUPPORT_SLEEP_CLOCK_ACCURACY_UPDATES | \
    LL_SUPPORT_REMOTE_PUBLIC_KEY_VALIDATION | \
    LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL | \
    LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL | \
    LL_SUPPORT_ISOCHRONOUS_BROADCASTER | \
    LL_SUPPORT_SYNCHRONIZED_RECEIVER | \
    LL_SUPPORT_LE_POWER_CONTROL_REQUEST | \
    LL_SUPPORT_LE_POWER_CONTROL_REQUEST1 | \
    LL_SUPPORT_LE_PATH_LOSS_MONITORING | \
    LL_SUPPORT_PERIODIC_ADVERTISING_ADI_SUPPORT | \
    LL_SUPPORT_CONNECTION_SUBRATING | \
    LL_SUPPORT_CHANNEL_CLASSIFICATION | \
    LL_SUPPORT_ADVERTISING_CODING_SELECTION | \
    LL_SUPPORT_DECISION_BASED_ADVERTISING_FILTERING | \
    LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER | \
    LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER | \
    LL_SUPPORT_UNSEGMENTED_FRAMED_MODE | \
    LL_SUPPORT_CHANNEL_SOUNDING | \
    LL_SUPPORT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION | \
    LL_SUPPORT_LE_EXTENDED_FEATURE_SET | \
    LL_SUPPORT_MONITORING_ADVERTISERS | \
    LL_SUPPORT_FRAME_SPACE_UPDATE | \
    0)



/***********************Bluetooth LE LL config **************************/
void ll_init_state_machine(_u8 number);

controller_error_code_e ll_reset(void);

_u64 ll_get_feature(void);
/***********************Bluetooth LE Advertising **************************/
typedef enum
{
    LL_ADV_IND                     = 0x00,//connectable and scannable undirected advertising,default.
    LL_ADV_DIRECT_IND_HIGH_DUTY    = 0x01,//connectable high duty directed advertising.
    LL_ADV_SCAN_IND                = 0x02,//scannable undirected advertising.
    LL_ADV_NONCONN_IND             = 0x03,//none connectable undirected advertising.
    LL_ADV_DIRECT_IND_LOW_DUTY     = 0x04,//connectable low duty directed advertising.
}ll_advertising_type_e;

typedef enum
{
    LL_PUBLIC_DEVICE_ADDRESS              = 0x00,
    LL_RANDOM_DEVICE_ADDRESS              = 0x01,
    LL_RESOLVABLE_PRIVATE_PUBLIC_ADDRESS  = 0x02,
    LL_RESOLVABLE_PRIVATE_RANDOM_ADDRESS  = 0x03,
}ll_own_address_type_e;

typedef enum
{
    LL_PUBLIC_DEVICE_OR_IDENTITY_ADDRESS  = 0x00,
    LL_RANDOM_DEVICE_OR_IDENTITY_ADDRESS  = 0x01,
}ll_peer_address_type_e;

typedef enum
{
    LL_FILTER_LIST_NOT_USE                        = 0x00,
    LL_FILTER_SCAN_REQUEST                        = 0x01,
    LL_FILTER_CONNECTION_REQUEST                  = 0x02,
    LL_FILTER_SCAN_REQUEST_AND_CONNECTION_REQUEST = 0x03,
}ll_advertising_filter_policy_e;

typedef enum
{
    LL_ADVERTISING_ENABLE  = 1,
    LL_ADVERTISING_DISABLE = 0,
}ll_advertising_enable_e;

controller_error_code_e ll_set_advertising_parameters(_u16 interval,\
                                                     ll_advertising_type_e type,\
                                                     ll_own_address_type_e ownAddressType,\
                                                     ll_peer_address_type_e peerAddressType,\
                                                     _u8* peerAddress,_u8 channelMap,\
                                                     ll_advertising_filter_policy_e policy);                
                                                    
controller_error_code_e ll_set_advertising_data(_u8* data,_u8 length);

controller_error_code_e ll_set_scan_response_data(_u8* data,_u8 length);

controller_error_code_e ll_set_advertising_enable(_u8 enable);

#endif
