#include"../config.h"

#ifndef BLE_CONTROLLER_LL_LL_CONFIG_H_
#define BLE_CONTROLLER_LL_LL_CONFIG_H_


/*************************** ALL BLE FEATRURES ******************************************/
//#define  BLE_SUPPORT_ENCRYPTION
//#define  BLE_SUPPORT_CONNECTION_PARAMETERS_REQUEST
//#define  BLE_SUPPORT_EXTENDED_REJECT
//#define  BLE_SUPPORT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE
//#define  BLE_SUPPORT_PING
//#define  BLE_SUPPORT_DATA_PACKET_LENGTH_EXTENSION
//#define  BLE_SUPPORT_PRIVACY
//#define  BLE_SUPPORT_EXTENDED_SCANNING_FILTER_POLICIES
//#define  BLE_SUPPORT_2M_PHY
//#define  BLE_SUPPORT_STABLE_MODULATION_INDEX_TX
//#define  BLE_SUPPORT_STABLE_MODULATION_INDEX_RX
//#define  BLE_SUPPORT_CODED_PHY
//#define  BLE_SUPPORT_EXTENDED_ADVERTISING
//#define  BLE_SUPPORT_PERIODIC_ADVERTISING
//#define  BLE_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2
//#define  BLE_SUPPORT_POWER_CLASS_1
//#define  BLE_SUPPORT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE
//#define  BLE_SUPPORT_CONNECTION_CTE_REQUEST
//#define  BLE_SUPPORT_CONNECTION_CTE_RESPONSE
//#define  BLE_SUPPORT_CONNECTIONLESS_CTE_TRANSMITTER
//#define  BLE_SUPPORT_CONNECTIONLESS_CTE_RECEIVER
//#define  BLE_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION
//#define  BLE_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION
//#define  BLE_SUPPORT_RECEIVING_CONSTANT_TONE_EXTENSIONS
//#define  BLE_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER
//#define  BLE_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT
//#define  BLE_SUPPORT_SLEEP_CLOCK_ACCURACY_UPDATES
//#define  BLE_SUPPORT_REMOTE_PUBLIC_KEY_VALIDATION
//#define  BLE_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL
//#define  BLE_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL
//#define  BLE_SUPPORT_ISOCHRONOUS_BROADCASTER
//#define  BLE_SUPPORT_SYNCHRONIZED_RECEIVER
//#define  BLE_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT
//#define  BLE_SUPPORT_POWER_CONTROL_REQUEST
//#define  BLE_SUPPORT_POWER_CONTROL_REQUEST1
//#define  BLE_SUPPORT_PATH_LOSS_MONITORING
//#define  BLE_SUPPORT_PERIODIC_ADVERTISING_ADI
//#define  BLE_SUPPORT_CONNECTION_SUBRATING
//#define  BLE_SUPPORT_CONNECTION_SUBRATING_HOST_SUPPORT
//#define  BLE_SUPPORT_CHANNEL_CLASSIFICATION
//#define  BLE_SUPPORT_ADVERTISING_CODING_SELECTION
//#define  BLE_SUPPORT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT
//#define  BLE_SUPPORT_DECISION_BASED_ADVERTISING_FILTERING
//#define  BLE_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER
//#define  BLE_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER
//#define  BLE_SUPPORT_UNSEGMENTED_FRAMED_MODE
//#define  BLE_SUPPORT_CHANNEL_SOUNDING
//#define  BLE_SUPPORT_CHANNEL_SOUNDING_HOST_SUPPORT
//#define  BLE_SUPPORT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION
//#define  BLE_SUPPORT_EXTENDED_FEATURE_SET
//#define  BLE_SUPPORT_MONITORING_ADVERTISERS
//#define  BLE_SUPPORT_FRAME_SPACE_UPDATE
/************************* BLE ROLE CONFIGURE *****************************/
#if defined (BLE_SUPPORT_ADV) 

#ifndef BLE_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2
#define BLE_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2
#endif

#endif 

#if defined(BLE_SUPPORT_SCAN) 

#endif 

#if defined(BLE_SUPPORT_CEN) 

#endif 

#if defined(BLE_SUPPORT_PER) 

#ifndef BLE_SUPPORT_ADV
#define BLE_SUPPORT_ADV
#endif

#endif 

#if defined(BLE_SUPPORT_CEN)||defined(BLE_SUPPORT_PER)
#define BLE_SUPPORT_CONN             y
#endif

#if defined(BLE_SUPPORT_CONN)
#define BLE_SUPPORT_CONNECTION_SUBRATING y
#endif

#if defined(BLE_SUPPORT_PDA) 

#ifndef BLE_SUPPORT_ADV
#define BLE_SUPPORT_ADV
#endif

#ifndef BLE_SUPPORT_EXTENDED_ADVERTISING
#define BLE_SUPPORT_EXTENDED_ADVERTISING
#endif

#ifndef BLE_SUPPORT_PERIODIC_ADVERTISING
#define BLE_SUPPORT_PERIODIC_ADVERTISING
#endif

#endif 

#if defined(BLE_SUPPORT_PDA_SYNC) 
#ifndef BLE_SUPPORT_SCAN
#define BLE_SUPPORT_SCAN
#endif

#ifndef BLE_SUPPORT_EXTENDED_ADVERTISING
#define BLE_SUPPORT_EXTENDED_ADVERTISING
#endif

#ifndef BLE_SUPPORT_PERIODIC_ADVERTISING
#define BLE_SUPPORT_PERIODIC_ADVERTISING
#endif
#endif 

#if defined(BLE_SUPPORT_PAWR) 


#endif 

#if defined(BLE_SUPPORT_PAWR_SYNC) 

#endif 

#if defined(BLE_SUPPORT_ISO_CEN) 

#endif 

#if defined(BLE_SUPPORT_ISO_PER) 

#endif 

#if defined(BLE_SUPPORT_ISO_BRD) 

#endif 

#if defined(BLE_SUPPORT_ISO_SYNC) 

#endif 

#if defined(BLE_SUPPORT_CS) 

#endif 



#if defined(BLE_SUPPORT_ISO_CEN)||defined(BLE_SUPPORT_ISO_PER)||defined(BLE_SUPPORT_ISO_BRD)||defined(BLE_SUPPORT_ISO_SYNC)
#define BLE_SUPPORT_ISO
#endif




#endif /* BLE_CONTROLLER_LL_LL_CONFIG_H_ */
