#ifndef LL_FEATURE_H_
#define LL_FEATURE_H_

#include"ll_config.h"
/***********************Bluetooth LE Feature define**************************/

#define LL_FEATURE_BIT_LE_ENCRYPTION                              BIT64(0)
#define LL_FEATURE_BIT_CONNECTION_PARAMETERS_REQUEST              BIT64(1)
#define LL_FEATURE_BIT_EXTENDED_REJECT                            BIT64(2)
#define LL_FEATURE_BIT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE     BIT64(3)
#define LL_FEATURE_BIT_LE_PING                                    BIT64(4)
#define LL_FEATURE_BIT_LE_DATA_PACKET_LENGTH_EXTENSION            BIT64(5)
#define LL_FEATURE_BIT_LL_PRIVACY                                 BIT64(6)
#define LL_FEATURE_BIT_EXTENDED_SCANNING_FILTER_POLICIES          BIT64(7)
#define LL_FEATURE_BIT_LE_2M_PHY                                  BIT64(8)
#define LL_FEATURE_BIT_STABLE_MODULATION_INDEX_TX                 BIT64(9)
#define LL_FEATURE_BIT_STABLE_MODULATION_INDEX_RX                 BIT64(10)
#define LL_FEATURE_BIT_LE_CODED_PHY                               BIT64(11)
#define LL_FEATURE_BIT_LE_EXTENDED_ADVERTISING                    BIT64(12)
#define LL_FEATURE_BIT_LE_PERIODIC_ADVERTISING                    BIT64(13)
#define LL_FEATURE_BIT_CHANNEL_SELECTION_ALGORITHM_2              BIT64(14)
#define LL_FEATURE_BIT_LE_POWER_CLASS_1                           BIT64(15)
#define LL_FEATURE_BIT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE  BIT64(16)
#define LL_FEATURE_BIT_CONNECTION_CTE_REQUEST                     BIT64(17)
#define LL_FEATURE_BIT_CONNECTION_CTE_RESPONSE                    BIT64(18)
#define LL_FEATURE_BIT_CONNECTIONLESS_CTE_TRANSMITTER             BIT64(19)
#define LL_FEATURE_BIT_CONNECTIONLESS_CTE_RECEIVER                BIT64(20)
#define LL_FEATURE_BIT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION  BIT64(21)
#define LL_FEATURE_BIT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION     BIT64(22)
#define LL_FEATURE_BIT_RECEIVING_CONSTANT_TONE_EXTENSIONS         BIT64(23)
#define LL_FEATURE_BIT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER  BIT64(24)
#define LL_FEATURE_BIT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT BIT64(25)
#define LL_FEATURE_BIT_SLEEP_CLOCK_ACCURACY_UPDATES               BIT64(26)
#define LL_FEATURE_BIT_REMOTE_PUBLIC_KEY_VALIDATION               BIT64(27)
#define LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL       BIT64(28)
#define LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL    BIT64(29)
#define LL_FEATURE_BIT_ISOCHRONOUS_BROADCASTER                    BIT64(30)
#define LL_FEATURE_BIT_SYNCHRONIZED_RECEIVER                      BIT64(31)
#define LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT  BIT64(32)
#define LL_FEATURE_BIT_LE_POWER_CONTROL_REQUEST                   BIT64(33)
#define LL_FEATURE_BIT_LE_POWER_CONTROL_REQUEST1                  BIT64(34)
#define LL_FEATURE_BIT_LE_PATH_LOSS_MONITORING                    BIT64(35)
#define LL_FEATURE_BIT_PERIODIC_ADVERTISING_ADI_SUPPORT           BIT64(36)
#define LL_FEATURE_BIT_CONNECTION_SUBRATING                       BIT64(37)
#define LL_FEATURE_BIT_CONNECTION_SUBRATING_HOST_SUPPORT          BIT64(38)
#define LL_FEATURE_BIT_CHANNEL_CLASSIFICATION                     BIT64(39)
#define LL_FEATURE_BIT_ADVERTISING_CODING_SELECTION               BIT64(40)
#define LL_FEATURE_BIT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT  BIT64(41)
#define LL_FEATURE_BIT_DECISION_BASED_ADVERTISING_FILTERING       BIT64(42)
#define LL_FEATURE_BIT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER  BIT64(43)
#define LL_FEATURE_BIT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER    BIT64(44)
#define LL_FEATURE_BIT_UNSEGMENTED_FRAMED_MODE                    BIT64(45)
#define LL_FEATURE_BIT_CHANNEL_SOUNDING                           BIT64(46)
#define LL_FEATURE_BIT_CHANNEL_SOUNDING_HOST_SUPPORT              BIT64(47)
#define LL_FEATURE_BIT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION   BIT64(48)
//reserved for specification developments purposes
#define LL_FEATURE_BIT_LE_EXTENDED_FEATURE_SET                    BIT64(63)
#define LL_FEATURE_BIT_MONITORING_ADVERTISERS                     BIT64(0)
#define LL_FEATURE_BIT_FRAME_SPACE_UPDATE                         BIT64(1)



/***********************Bluetooth LE Feature Configure**************************/
#ifdef  BLE_SUPPORT_ENCRYPTION
#define LL_SUPPORT_LE_ENCRYPTION LL_FEATURE_BIT_LE_ENCRYPTION
#else
#define LL_SUPPORT_LE_ENCRYPTION 0ULL
#endif

#ifdef  BLE_SUPPORT_CONNECTION_PARAMETERS_REQUEST
#define LL_SUPPORT_CONNECTION_PARAMETERS_REQUEST LL_FEATURE_BIT_CONNECTION_PARAMETERS_REQUEST
#else
#define LL_SUPPORT_CONNECTION_PARAMETERS_REQUEST 0ULL
#endif

#ifdef  BLE_SUPPORT_EXTENDED_REJECT
#define LL_SUPPORT_EXTENDED_REJECT LL_FEATURE_BIT_EXTENDED_REJECT
#else
#define LL_SUPPORT_EXTENDED_REJECT 0ULL
#endif

#ifdef  BLE_SUPPORT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE
#define LL_SUPPORT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE LL_FEATURE_BIT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE
#else
#define LL_SUPPORT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE 0ULL
#endif

#ifdef  BLE_SUPPORT_PING
#define LL_SUPPORT_LE_PING LL_FEATURE_BIT_LE_PING
#else
#define LL_SUPPORT_LE_PING 0ULL
#endif

#ifdef  BLE_SUPPORT_DATA_PACKET_LENGTH_EXTENSION
#define LL_SUPPORT_LE_DATA_PACKET_LENGTH_EXTENSION LL_FEATURE_BIT_LE_DATA_PACKET_LENGTH_EXTENSION
#else
#define LL_SUPPORT_LE_DATA_PACKET_LENGTH_EXTENSION 0ULL
#endif

#ifdef  BLE_SUPPORT_PRIVACY
#define LL_SUPPORT_LL_PRIVACY LL_FEATURE_BIT_LL_PRIVACY
#else
#define LL_SUPPORT_LL_PRIVACY 0ULL
#endif

#ifdef  BLE_SUPPORT_EXTENDED_SCANNING_FILTER_POLICIES
#define LL_SUPPORT_EXTENDED_SCANNING_FILTER_POLICIES LL_FEATURE_BIT_EXTENDED_SCANNING_FILTER_POLICIES
#else
#define LL_SUPPORT_EXTENDED_SCANNING_FILTER_POLICIES 0ULL
#endif

#ifdef  BLE_SUPPORT_2M_PHY
#define LL_SUPPORT_LE_2M_PHY LL_FEATURE_BIT_LE_2M_PHY
#else
#define LL_SUPPORT_LE_2M_PHY 0ULL
#endif

#ifdef  BLE_SUPPORT_STABLE_MODULATION_INDEX_TX
#define LL_SUPPORT_STABLE_MODULATION_INDEX_TX LL_FEATURE_BIT_STABLE_MODULATION_INDEX_TX
#else
#define LL_SUPPORT_STABLE_MODULATION_INDEX_TX 0ULL
#endif

#ifdef  BLE_SUPPORT_STABLE_MODULATION_INDEX_RX
#define LL_SUPPORT_STABLE_MODULATION_INDEX_RX LL_FEATURE_BIT_STABLE_MODULATION_INDEX_RX
#else
#define LL_SUPPORT_STABLE_MODULATION_INDEX_RX 0ULL
#endif

#ifdef  BLE_SUPPORT_CODED_PHY
#define LL_SUPPORT_LE_CODED_PHY LL_FEATURE_BIT_LE_CODED_PHY
#else
#define LL_SUPPORT_LE_CODED_PHY 0ULL
#endif

#ifdef  BLE_SUPPORT_EXTENDED_ADVERTISING
#define LL_SUPPORT_LE_EXTENDED_ADVERTISING LL_FEATURE_BIT_LE_EXTENDED_ADVERTISING
#else
#define LL_SUPPORT_LE_EXTENDED_ADVERTISING 0ULL
#endif

#ifdef  BLE_SUPPORT_PERIODIC_ADVERTISING
#define LL_SUPPORT_LE_PERIODIC_ADVERTISING LL_FEATURE_BIT_LE_PERIODIC_ADVERTISING
#else
#define LL_SUPPORT_LE_PERIODIC_ADVERTISING 0ULL
#endif

#ifdef  BLE_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2
#define LL_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2 LL_FEATURE_BIT_CHANNEL_SELECTION_ALGORITHM_2
#else
#define LL_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2 0ULL
#endif

#ifdef  BLE_SUPPORT_POWER_CLASS_1
#define LL_SUPPORT_LE_POWER_CLASS_1 LL_FEATURE_BIT_LE_POWER_CLASS_1
#else
#define LL_SUPPORT_LE_POWER_CLASS_1 0ULL
#endif

#ifdef  BLE_SUPPORT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE
#define LL_SUPPORT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE LL_FEATURE_BIT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE
#else
#define LL_SUPPORT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE 0ULL
#endif

#ifdef  BLE_SUPPORT_CONNECTION_CTE_REQUEST
#define LL_SUPPORT_CONNECTION_CTE_REQUEST LL_FEATURE_BIT_CONNECTION_CTE_REQUEST
#else
#define LL_SUPPORT_CONNECTION_CTE_REQUEST 0ULL
#endif

#ifdef  BLE_SUPPORT_CONNECTION_CTE_RESPONSE
#define LL_SUPPORT_CONNECTION_CTE_RESPONSE LL_FEATURE_BIT_CONNECTION_CTE_RESPONSE
#else
#define LL_SUPPORT_CONNECTION_CTE_RESPONSE 0ULL
#endif

#ifdef  BLE_SUPPORT_CONNECTIONLESS_CTE_TRANSMITTER
#define LL_SUPPORT_CONNECTIONLESS_CTE_TRANSMITTER LL_FEATURE_BIT_CONNECTIONLESS_CTE_TRANSMITTER
#else
#define LL_SUPPORT_CONNECTIONLESS_CTE_TRANSMITTER 0ULL
#endif

#ifdef  BLE_SUPPORT_CONNECTIONLESS_CTE_RECEIVER
#define LL_SUPPORT_CONNECTIONLESS_CTE_RECEIVER LL_FEATURE_BIT_CONNECTIONLESS_CTE_RECEIVER
#else
#define LL_SUPPORT_CONNECTIONLESS_CTE_RECEIVER 0ULL
#endif

#ifdef  BLE_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION
#define LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION LL_FEATURE_BIT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION
#else
#define LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION 0ULL
#endif

#ifdef  BLE_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION
#define LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION LL_FEATURE_BIT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION
#else
#define LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION 0ULL
#endif

#ifdef  BLE_SUPPORT_RECEIVING_CONSTANT_TONE_EXTENSIONS
#define LL_SUPPORT_RECEIVING_CONSTANT_TONE_EXTENSIONS LL_FEATURE_BIT_RECEIVING_CONSTANT_TONE_EXTENSIONS
#else
#define LL_SUPPORT_RECEIVING_CONSTANT_TONE_EXTENSIONS 0ULL
#endif

#ifdef  BLE_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER
#define LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER LL_FEATURE_BIT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER
#else
#define LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER 0ULL
#endif

#ifdef  BLE_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT
#define LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT LL_FEATURE_BIT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT
#else
#define LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT 0ULL
#endif

#ifdef  BLE_SUPPORT_SLEEP_CLOCK_ACCURACY_UPDATES
#define LL_SUPPORT_SLEEP_CLOCK_ACCURACY_UPDATES LL_FEATURE_BIT_SLEEP_CLOCK_ACCURACY_UPDATES
#else
#define LL_SUPPORT_SLEEP_CLOCK_ACCURACY_UPDATES 0ULL
#endif

#ifdef  BLE_SUPPORT_REMOTE_PUBLIC_KEY_VALIDATION
#define LL_SUPPORT_REMOTE_PUBLIC_KEY_VALIDATION LL_FEATURE_BIT_REMOTE_PUBLIC_KEY_VALIDATION
#else
#define LL_SUPPORT_REMOTE_PUBLIC_KEY_VALIDATION 0ULL
#endif

#ifdef  BLE_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL
#else
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL 0ULL
#endif

#ifdef  BLE_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL
#else
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL 0ULL
#endif

#ifdef  BLE_SUPPORT_ISOCHRONOUS_BROADCASTER
#define LL_SUPPORT_ISOCHRONOUS_BROADCASTER LL_FEATURE_BIT_ISOCHRONOUS_BROADCASTER
#else
#define LL_SUPPORT_ISOCHRONOUS_BROADCASTER 0ULL
#endif

#ifdef  BLE_SUPPORT_SYNCHRONIZED_RECEIVER
#define LL_SUPPORT_SYNCHRONIZED_RECEIVER LL_FEATURE_BIT_SYNCHRONIZED_RECEIVER
#else
#define LL_SUPPORT_SYNCHRONIZED_RECEIVER 0ULL
#endif

#ifdef  BLE_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT LL_FEATURE_BIT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT
#else
#define LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_HOST_SUPPORT 0ULL
#endif

#ifdef  BLE_SUPPORT_POWER_CONTROL_REQUEST
#define LL_SUPPORT_LE_POWER_CONTROL_REQUEST LL_FEATURE_BIT_LE_POWER_CONTROL_REQUEST
#else
#define LL_SUPPORT_LE_POWER_CONTROL_REQUEST 0ULL
#endif

#ifdef  BLE_SUPPORT_POWER_CONTROL_REQUEST1
#define LL_SUPPORT_LE_POWER_CONTROL_REQUEST1 LL_FEATURE_BIT_LE_POWER_CONTROL_REQUEST1
#else
#define LL_SUPPORT_LE_POWER_CONTROL_REQUEST1 0ULL
#endif

#ifdef  BLE_SUPPORT_PATH_LOSS_MONITORING
#define LL_SUPPORT_LE_PATH_LOSS_MONITORING LL_FEATURE_BIT_LE_PATH_LOSS_MONITORING
#else
#define LL_SUPPORT_LE_PATH_LOSS_MONITORING 0ULL
#endif

#ifdef  BLE_SUPPORT_PERIODIC_ADVERTISING_ADI
#define LL_SUPPORT_PERIODIC_ADVERTISING_ADI_SUPPORT LL_FEATURE_BIT_PERIODIC_ADVERTISING_ADI_SUPPORT
#else
#define LL_SUPPORT_PERIODIC_ADVERTISING_ADI_SUPPORT 0ULL
#endif

#ifdef  BLE_SUPPORT_CONNECTION_SUBRATING
#define LL_SUPPORT_CONNECTION_SUBRATING LL_FEATURE_BIT_CONNECTION_SUBRATING
#else
#define LL_SUPPORT_CONNECTION_SUBRATING 0ULL
#endif

#ifdef  BLE_SUPPORT_CONNECTION_SUBRATING_HOST_SUPPORT
#define LL_SUPPORT_CONNECTION_SUBRATING_HOST_SUPPORT LL_FEATURE_BIT_CONNECTION_SUBRATING_HOST_SUPPORT
#else
#define LL_SUPPORT_CONNECTION_SUBRATING_HOST_SUPPORT 0ULL
#endif

#ifdef  BLE_SUPPORT_CHANNEL_CLASSIFICATION
#define LL_SUPPORT_CHANNEL_CLASSIFICATION LL_FEATURE_BIT_CHANNEL_CLASSIFICATION
#else
#define LL_SUPPORT_CHANNEL_CLASSIFICATION 0ULL
#endif

#ifdef  BLE_SUPPORT_ADVERTISING_CODING_SELECTION
#define LL_SUPPORT_ADVERTISING_CODING_SELECTION LL_FEATURE_BIT_ADVERTISING_CODING_SELECTION
#else
#define LL_SUPPORT_ADVERTISING_CODING_SELECTION 0ULL
#endif

#ifdef  BLE_SUPPORT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT
#define LL_SUPPORT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT LL_FEATURE_BIT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT
#else
#define LL_SUPPORT_ADVERTISING_CODING_SELECTION_HOST_SUPPORT 0ULL
#endif

#ifdef  BLE_SUPPORT_DECISION_BASED_ADVERTISING_FILTERING
#define LL_SUPPORT_DECISION_BASED_ADVERTISING_FILTERING LL_FEATURE_BIT_DECISION_BASED_ADVERTISING_FILTERING
#else
#define LL_SUPPORT_DECISION_BASED_ADVERTISING_FILTERING           0ULL
#endif

#ifdef  BLE_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER
#define LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER LL_FEATURE_BIT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER
#else
#define LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER 0ULL
#endif

#ifdef  BLE_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER
#define LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER LL_FEATURE_BIT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER
#else
#define LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER    0ULL
#endif

#ifdef  BLE_SUPPORT_UNSEGMENTED_FRAMED_MODE
#define LL_SUPPORT_UNSEGMENTED_FRAMED_MODE LL_FEATURE_BIT_UNSEGMENTED_FRAMED_MODE
#else
#define LL_SUPPORT_UNSEGMENTED_FRAMED_MODE                        0ULL
#endif

#ifdef  BLE_SUPPORT_CHANNEL_SOUNDING
#define LL_SUPPORT_CHANNEL_SOUNDING LL_FEATURE_BIT_CHANNEL_SOUNDING
#else
#define LL_SUPPORT_CHANNEL_SOUNDING                               0ULL
#endif

#ifdef  BLE_SUPPORT_CHANNEL_SOUNDING_HOST_SUPPORT
#define LL_SUPPORT_CHANNEL_SOUNDING_HOST_SUPPORT LL_FEATURE_BIT_CHANNEL_SOUNDING_HOST_SUPPORT
#else
#define LL_SUPPORT_CHANNEL_SOUNDING_HOST_SUPPORT 0ULL
#endif

#ifdef  BLE_SUPPORT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION
#define LL_SUPPORT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION LL_FEATURE_BIT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION
#else
#define LL_SUPPORT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION 0ULL
#endif

#ifdef  BLE_SUPPORT_EXTENDED_FEATURE_SET
#define LL_SUPPORT_LE_EXTENDED_FEATURE_SET LL_FEATURE_BIT_LE_EXTENDED_FEATURE_SET
#else
#define LL_SUPPORT_LE_EXTENDED_FEATURE_SET 0ULL
#endif

#ifdef  BLE_SUPPORT_MONITORING_ADVERTISERS
#define LL_SUPPORT_MONITORING_ADVERTISERS LL_FEATURE_BIT_MONITORING_ADVERTISERS
#else
#define LL_SUPPORT_MONITORING_ADVERTISERS 0ULL
#endif

#ifdef  BLE_SUPPORT_FRAME_SPACE_UPDATE
#define LL_SUPPORT_FRAME_SPACE_UPDATE LL_FEATURE_BIT_FRAME_SPACE_UPDATE
#else
#define LL_SUPPORT_FRAME_SPACE_UPDATE 0ULL
#endif

#define LL_FEATURE_SUPPORT_BYTE_0 (\
    LL_SUPPORT_LE_ENCRYPTION | \
    LL_SUPPORT_CONNECTION_PARAMETERS_REQUEST | \
    LL_SUPPORT_EXTENDED_REJECT | \
    LL_SUPPORT_PERIPHERAL_INITIATED_FEATURES_EXCHANGE | \
    LL_SUPPORT_LE_PING | \
    LL_SUPPORT_LE_DATA_PACKET_LENGTH_EXTENSION | \
    LL_SUPPORT_LL_PRIVACY | \
    LL_SUPPORT_EXTENDED_SCANNING_FILTER_POLICIES | \
    0)

#define LL_FEATURE_SUPPORT_BYTE_1 (\
    LL_SUPPORT_LE_2M_PHY>>8 | \
    LL_SUPPORT_STABLE_MODULATION_INDEX_TX>>8 | \
    LL_SUPPORT_STABLE_MODULATION_INDEX_RX>>8 | \
    LL_SUPPORT_LE_CODED_PHY>>8 | \
    LL_SUPPORT_LE_EXTENDED_ADVERTISING>>8 | \
    LL_SUPPORT_LE_PERIODIC_ADVERTISING>>8 | \
    LL_SUPPORT_CHANNEL_SELECTION_ALGORITHM_2>>8 | \
    LL_SUPPORT_LE_POWER_CLASS_1>>8 | \
    0)

#define LL_FEATURE_SUPPORT_BYTE_2 (\
    LL_SUPPORT_MINIMUM_NUMBER_OF_USED_CHANNELS_PROCEDURE>>16 | \
    LL_SUPPORT_CONNECTION_CTE_REQUEST>>16 | \
    LL_SUPPORT_CONNECTION_CTE_RESPONSE>>16 | \
    LL_SUPPORT_CONNECTIONLESS_CTE_TRANSMITTER>>16 | \
    LL_SUPPORT_CONNECTIONLESS_CTE_RECEIVER>>16 | \
    LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_TRANSMISSION>>16 | \
    LL_SUPPORT_ANTENNA_SWITCHING_DURING_CTE_RECEPTION>>16 | \
    LL_SUPPORT_RECEIVING_CONSTANT_TONE_EXTENSIONS>>16 | \
    0)

#define LL_FEATURE_SUPPORT_BYTE_3 (\
    LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_SENDER>>24 | \
    LL_SUPPORT_PERIODIC_ADVERTISING_SYNC_TRANSFER_RECIPIENT>>24 | \
    LL_SUPPORT_SLEEP_CLOCK_ACCURACY_UPDATES>>24 | \
    LL_SUPPORT_REMOTE_PUBLIC_KEY_VALIDATION>>24 | \
    LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_CENTRAL>>24 | \
    LL_SUPPORT_CONNECTED_ISOCHRONOUS_STREAM_PERIPHERAL>>24 | \
    LL_SUPPORT_ISOCHRONOUS_BROADCASTER>>24 | \
    LL_SUPPORT_SYNCHRONIZED_RECEIVER>>24 | \
    0)

#define LL_FEATURE_SUPPORT_BYTE_4 (\
    LL_SUPPORT_LE_POWER_CONTROL_REQUEST>>32 | \
    LL_SUPPORT_LE_POWER_CONTROL_REQUEST1>>32 | \
    LL_SUPPORT_LE_PATH_LOSS_MONITORING>>32 | \
    LL_SUPPORT_PERIODIC_ADVERTISING_ADI_SUPPORT>>32 | \
    LL_SUPPORT_CONNECTION_SUBRATING>>32 | \
    LL_SUPPORT_CHANNEL_CLASSIFICATION>>32 | \
    0)

#define LL_FEATURE_SUPPORT_BYTE_5 (\
    LL_SUPPORT_ADVERTISING_CODING_SELECTION>>40 | \
    LL_SUPPORT_DECISION_BASED_ADVERTISING_FILTERING>>40 | \
    LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER>>40 | \
    LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_SCANNER>>40 | \
    LL_SUPPORT_UNSEGMENTED_FRAMED_MODE>>40 | \
    LL_SUPPORT_CHANNEL_SOUNDING>>40 | \
    LL_SUPPORT_CHANNEL_SOUNDING_HOST_SUPPORT>>40| \
    0)

#define LL_FEATURE_SUPPORT_BYTE_6 (LL_SUPPORT_CHANNEL_SOUNDING_TONE_QUALITY_INDICATION>>48|0)

#define LL_FEATURE_SUPPORT_BYTE_7 (LL_SUPPORT_LE_EXTENDED_FEATURE_SET>>56|0)

#define LL_FEATURE_SUPPORT_BYTE_8 (\
    LL_SUPPORT_MONITORING_ADVERTISERS| \
    LL_SUPPORT_FRAME_SPACE_UPDATE| \
    0)
#endif
