
#define BLE_SUPPORT_ADV   y

#define BLE_SUPPORT_EXTENDED_ADVERTISING y
//
#define BLE_SUPPORT_PERIODIC_ADVERTISING y

#define BLE_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER y

// #define BLE_SUPPORT_SCAN  y

 #define BLE_SUPPORT_CEN  y

 #define BLE_SUPPORT_PER  y
