#include"common/txCommon.h"
#include"../../ll_internal.h"
#include"../../ll.h"

#define BLE_ADV_ACCESS_CODE   0xd6be898e
#define BLE_ADV_CRC_INIT      0x555555

#define BLE_ADV_MAX_LENGTH    37
#define BLE_ADV_INTERVAL_UNIT 1250

typedef enum
{
    ADV_EVENT,
    #if(LL_SUPPORT_LE_EXTENDED_ADVERTISING==1)
    ADV_EXTENDED_EVENT,
    #endif
    #if(LL_SUPPORT_LE_PERIODIC_ADVERTISING==1)
    ADV_PERIODIC_EVENT,
    #endif
    #if(LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER==1)
    ADV_PERIODIC_WITH_RSP_EVENT,
    #endif
}adv_event_class_e;

typedef enum
{
    ADV_EVENT_CONNECTABLE_SCANNABLE_UNDIRECTED,
    ADV_EVENT_CONNECTABLE_DIRECTED,
    ADV_EVENT_SCANNABLE_UNDIRECTED,
    ADV_EVENT_NON_CONNECTABLE_NON_SCANNABLE_UNDIRECTED,
    #if(LL_SUPPORT_LE_EXTENDED_ADVERTISING==1)
    ADV_EVENT_EXTENDED_CONNECTABLE_DIRECTED,
    ADV_EVENT_EXTENDED_CONNECTABLE_UNDIRECTED,
    ADV_EVENT_EXTENDED_SCANNABLE_DIRECTED,
    ADV_EVENT_EXTENDED_SCANNABLE_UNDIRECTED,
    ADV_EVENT_EXTENDED_NON_CONNECTABLE_NON_SCANNABLE_DIRECTED,
    ADV_EVENT_EXTENDED_NON_CONNECTABLE_NON_SCANNABLE_UNDIRECTED,
    #endif
    #if(LL_SUPPORT_LE_PERIODIC_ADVERTISING==1)
    ADV_EVENT_EXTENDED_PERIODIC,
    #endif
    #if(LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER==1)
    ADV_EVENT_EXTENDED_PERIODIC_WITH_RESPONSE,
    #endif
}adv_event_type_e;

int ble_ll_enter_advertising_state(ble_ll_event_e event);
