/*
 * adv_internal.h
 *
 *  Created on: 2025年12月1日
 *      Author: Admin
 */

#ifndef BLE_CONTROLLER_LL_MODULE_ADV_ADV_INTERNAL_H_
#define BLE_CONTROLLER_LL_MODULE_ADV_ADV_INTERNAL_H_

#include"../../ll_internal.h"

#define BLE_ADV_ACCESS_CODE             0xd6be898e
#define BLE_ADV_CRC_INIT                0x555555


#define BLE_ADV_EXTENDED_HEADER_MAX_LEN 64
#define BLE_ADV_INTERVAL_UNIT           1250

#define BLE_ADV_DEFAULT_RX_TIMEOUT_US  (100+PACKET_DEFAULT_TIFS_TIME)


typedef enum
{
    ADV_EVENT,
    #if(LL_SUPPORT_LE_EXTENDED_ADVERTISING)
    ADV_EXTENDED_EVENT,
    ADV_CHAINED_EVENT,
    #endif
    #if(LL_SUPPORT_LE_PERIODIC_ADVERTISING)
    ADV_PERIODIC_EVENT,
    #endif
    #if(LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER)
    ADV_PERIODIC_WITH_RSP_EVENT,
    #endif
}adv_event_class_e;

typedef enum
{
    ADV_PDU_CLASS_LEG,
    ADV_PDU_CLASS_SCAN_RSP,
    ADV_PDU_CLASS_CONN_RSP,
    ADV_PDU_CLASS_EXT,
    ADV_PDU_CLASS_AUX,
    ADV_PDU_CLASS_CHAIN,
    ADV_PDU_CLASS_SYNC,
}adv_pdu_class_e;


typedef enum
{
    ADV_SCH_MAP_PRI       = BIT(0),
	#if(LL_SUPPORT_LE_EXTENDED_ADVERTISING)
    ADV_SCH_MAP_AUX       = BIT(1),
    ADV_SCH_MAP_AUX_CHAIN = BIT(2),
	#endif
	#if (LL_SUPPORT_LE_PERIODIC_ADVERTISING)
    ADV_SCH_MAP_PA        = BIT(3),
    ADV_SCH_MAP_PA_CHAIN  = BIT(4),
	#endif
	#if (LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER)
    ADV_SCH_MAP_PAWR      = BIT(5),
	#endif
	ADV_SCH_MAP_ALL       = ADV_SCH_MAP_PRI
	#if(LL_SUPPORT_LE_EXTENDED_ADVERTISING)
					       |ADV_SCH_MAP_AUX
						   |ADV_SCH_MAP_AUX_CHAIN
	#endif
	#if (LL_SUPPORT_LE_PERIODIC_ADVERTISING)
						   |ADV_SCH_MAP_PA
						   |ADV_SCH_MAP_PA_CHAIN
	#endif
	#if (LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER)
						   |ADV_SCH_MAP_PAWR
	#endif
} adv_ext_sch_map_e;


typedef enum
{
    ADV_EVENT_CONNECTABLE_SCANNABLE_UNDIRECTED,
    ADV_EVENT_CONNECTABLE_DIRECTED,
    ADV_EVENT_SCANNABLE_UNDIRECTED,
    ADV_EVENT_NON_CONNECTABLE_NON_SCANNABLE_UNDIRECTED,
    #if(LL_SUPPORT_LE_EXTENDED_ADVERTISING)
    ADV_EVENT_EXTENDED_CONNECTABLE_DIRECTED,
    ADV_EVENT_EXTENDED_CONNECTABLE_UNDIRECTED,
    ADV_EVENT_EXTENDED_SCANNABLE_DIRECTED,
    ADV_EVENT_EXTENDED_SCANNABLE_UNDIRECTED,
    ADV_EVENT_EXTENDED_NON_CONNECTABLE_NON_SCANNABLE_DIRECTED_WITH_AUXILIARY,
    ADV_EVENT_EXTENDED_NON_CONNECTABLE_NON_SCANNABLE_UNDIRECTED_WITH_AUXILIARY,
    ADV_EVENT_EXTENDED_NON_CONNECTABLE_NON_SCANNABLE_DIRECTED_WITHOUT_AUXILIARY,
    ADV_EVENT_EXTENDED_NON_CONNECTABLE_NON_SCANNABLE_UNDIRECTED_WITHOUT_AUXILIARY,
    #endif
    #if(LL_SUPPORT_LE_PERIODIC_ADVERTISING)
    ADV_EVENT_EXTENDED_PERIODIC,
    #endif
    #if(LL_SUPPORT_PERIODIC_ADVERTISING_WITH_RESPONSES_ADVERTISER)
    ADV_EVENT_EXTENDED_PERIODIC_WITH_RESPONSE,
    #endif
}adv_event_type_e;

int ble_ll_enter_advertising_state(ble_ll_event_e event);


#endif /* BLE_CONTROLLER_LL_MODULE_ADV_ADV_INTERNAL_H_ */
